### Wetter Daten laden (Von 1990 bis 2023)

### British Columbia (BC)

In [1]:
#Cariboo Region (Williams Lake Area)
#→ 52.15, -122.15

import pandas as pd

pfad = "../data/import weather data/import data/British Columbia/open-meteo-52.55N122.18W978m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.54833,-122.17876,1990-01-01,-4.5,-0.7,88,0.6,135,0.22,2.0,16.5,9.4,74
1,52.54833,-122.17876,1990-01-02,-12.9,-6.4,80,1.6,121,0.13,5.0,11.5,6.8,69
2,52.54833,-122.17876,1990-01-03,-7.0,-4.6,85,9.5,133,0.17,24.0,13.5,12.2,79
3,52.54833,-122.17876,1990-01-04,-6.8,-4.0,88,5.1,129,0.19,11.0,15.0,10.3,80
4,52.54833,-122.17876,1990-01-05,-3.4,1.2,83,2.4,136,0.38,7.0,23.6,16.3,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.54833,-122.17876,2022-12-28,-1.6,0.3,93,1.5,307,0.21,8.0,10.8,5.9,73
12050,52.54833,-122.17876,2022-12-29,-5.7,-2.5,89,0.0,137,0.21,0.0,17.4,9.7,72
12051,52.54833,-122.17876,2022-12-30,-3.5,-0.7,87,2.0,125,0.23,11.0,16.0,13.8,79
12052,52.54833,-122.17876,2022-12-31,-3.6,-2.2,91,4.1,128,0.16,7.0,12.1,7.8,86
12053,52.54833,-122.17876,2023-01-01,-6.1,-2.7,91,0.0,154,0.19,0.0,7.8,5.0,78

In [ ]:
#Okanagan – feueranfälligste Region in BC
#→ 49.80, -119.60

pfad = "../data/import weather data/import data/British Columbia/open-meteo-49.81N119.69W339m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_2

In [ ]:
#Peace River Forest / Fort St. John Hinterland
#→ 56.30, -121.00


pfad = "../data/import weather data/import data/British Columbia/open-meteo-56.27N121.05W789m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_3

### Daten zusammenführen pro Provinz und Durchschnitt berechnen

In [33]:

# in Datetime umwandeln
for df in [British_Columbia_1, British_Columbia_2, British_Columbia_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [British_Columbia_1, British_Columbia_2, British_Columbia_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
British_Columbia_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

British_Columbia_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-3.766667,0.466667,86.000000,72.666667,1.400000,5.666667,9.166667,12.733333,219.000000,0.260000
1,1990-01-02,-10.066667,-5.633333,73.333333,57.333333,1.100000,5.000000,7.066667,10.566667,125.666667,0.233333
2,1990-01-03,-9.500000,-6.966667,79.000000,65.333333,4.433333,14.000000,8.366667,10.400000,111.666667,0.176667
3,1990-01-04,-9.166667,-6.366667,84.000000,75.666667,4.033333,12.000000,6.766667,9.633333,113.333333,0.176667
4,1990-01-05,-6.866667,-0.800000,83.666667,72.000000,2.666667,6.333333,10.233333,14.333333,147.666667,0.220000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-4.500000,-2.866667,86.666667,75.666667,1.900000,10.666667,4.933333,7.800000,290.333333,0.180000
12050,2022-12-29,-7.900000,-4.166667,88.000000,76.666667,0.000000,0.000000,6.833333,11.166667,142.333333,0.176667
12051,2022-12-30,-6.100000,-2.766667,87.000000,79.666667,2.200000,9.000000,7.900000,10.566667,171.333333,0.193333
12052,2022-12-31,-5.733333,-3.100000,89.000000,81.666667,1.633333,3.666667,5.100000,7.800000,208.333333,0.196667
12053,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

### Durschnitt pro Monat

In [37]:

British_Columbia_mean['time'] = pd.to_datetime(British_Columbia_mean['time'])

# Monats-Durchschnitt für alle Variablen
British_Columbia_monthly_mean = (
    British_Columbia_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

British_Columbia_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-7.217204,-3.096774,80.827957,67.301075,1.897849,5.365591,8.690323,12.411828,195.720430,0.305269
1,1990-02-01,-8.708333,-2.703571,74.023810,55.714286,1.233333,4.000000,8.808333,12.864286,190.511905,0.605714
2,1990-03-01,-0.410753,5.854839,70.774194,46.817204,0.783871,2.591398,7.102151,11.177419,198.150538,1.463763
3,1990-04-01,5.446667,11.931111,65.322222,38.933333,1.227778,3.522222,6.862222,11.044444,186.688889,2.393444
4,1990-05-01,10.031183,16.084946,69.774194,42.430108,2.725806,6.043011,6.849462,11.625806,201.365591,2.998065
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.718889,21.870000,62.866667,34.522222,0.834444,1.366667,7.303333,12.341111,226.355556,2.794667
393,2022-10-01,9.849462,15.419355,67.139785,42.569892,0.772043,1.978495,8.088172,13.237634,201.344086,1.592903
394,2022-11-01,-4.906667,-1.096667,75.155556,59.755556,1.555556,4.066667,8.901111,12.875556,193.388889,0.451000
395,2022-12-01,-12.351613,-8.421505,79.559140,68.365591,1.718280,5.344086,7.688172,11.604301,208.806452,0.193871
396,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

### Alberta

In [ ]:
#Fort McMurray Forest Zone
#→ 56.75, -111.45