### Wetter Daten laden (Von 1990 bis 2023)

### British Columbia (BC)

In [1]:
#Cariboo Region (Williams Lake Area)
#→ 52.15, -122.15

import pandas as pd

pfad = "../data/import weather data/import data/British Columbia/open-meteo-52.55N122.18W978m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.54833,-122.17876,1990-01-01,-4.5,-0.7,88,0.6,135,0.22,2.0,16.5,9.4,74
1,52.54833,-122.17876,1990-01-02,-12.9,-6.4,80,1.6,121,0.13,5.0,11.5,6.8,69
2,52.54833,-122.17876,1990-01-03,-7.0,-4.6,85,9.5,133,0.17,24.0,13.5,12.2,79
3,52.54833,-122.17876,1990-01-04,-6.8,-4.0,88,5.1,129,0.19,11.0,15.0,10.3,80
4,52.54833,-122.17876,1990-01-05,-3.4,1.2,83,2.4,136,0.38,7.0,23.6,16.3,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.54833,-122.17876,2022-12-28,-1.6,0.3,93,1.5,307,0.21,8.0,10.8,5.9,73
12050,52.54833,-122.17876,2022-12-29,-5.7,-2.5,89,0.0,137,0.21,0.0,17.4,9.7,72
12051,52.54833,-122.17876,2022-12-30,-3.5,-0.7,87,2.0,125,0.23,11.0,16.0,13.8,79
12052,52.54833,-122.17876,2022-12-31,-3.6,-2.2,91,4.1,128,0.16,7.0,12.1,7.8,86
12053,52.54833,-122.17876,2023-01-01,-6.1,-2.7,91,0.0,154,0.19,0.0,7.8,5.0,78

In [2]:
#Okanagan – feueranfälligste Region in BC
#→ 49.80, -119.60

pfad = "../data/import weather data/import data/British Columbia/open-meteo-49.81N119.69W339m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,49.806675,-119.6875,1990-01-01,0.2,3.0,94,0.3,170,0.34,3.0,9.3,7.6,78
1,49.806675,-119.6875,1990-01-02,-0.2,2.3,78,0.8,244,0.41,5.0,8.3,6.8,50
2,49.806675,-119.6875,1990-01-03,-1.8,1.1,84,0.9,188,0.25,5.0,7.6,6.0,53
3,49.806675,-119.6875,1990-01-04,-0.5,3.6,87,4.0,166,0.28,14.0,7.3,5.6,80
4,49.806675,-119.6875,1990-01-05,1.8,4.0,87,1.3,188,0.19,4.0,7.8,6.0,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,49.806675,-119.6875,2022-12-28,3.5,5.1,88,2.6,213,0.25,18.0,6.8,4.9,80
12050,49.806675,-119.6875,2022-12-29,-2.1,3.4,86,0.0,288,0.26,0.0,8.8,6.2,73
12051,49.806675,-119.6875,2022-12-30,0.5,3.3,87,4.6,314,0.28,16.0,6.2,4.4,80
12052,49.806675,-119.6875,2022-12-31,0.3,4.1,88,0.8,277,0.36,4.0,6.5,4.9,73
12053,49.806675,-119.6875,2023-01-01,1.7,4.1,82,2.0,217,0.40,6.0,7.0,5.0,66

In [3]:
#Peace River Forest / Fort St. John Hinterland
#→ 56.30, -121.00


pfad = "../data/import weather data/import data/British Columbia/open-meteo-56.27N121.05W789m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,56.274162,-121.05373,1990-01-01,-7.0,-0.9,76,3.3,352,0.22,12.0,12.4,10.5,66
1,56.274162,-121.05373,1990-01-02,-17.1,-12.8,62,0.9,12,0.16,5.0,11.9,7.6,53
2,56.274162,-121.05373,1990-01-03,-19.7,-17.4,68,2.9,14,0.11,13.0,10.1,6.9,64
3,56.274162,-121.05373,1990-01-04,-20.2,-18.7,77,3.0,45,0.06,11.0,6.6,4.4,67
4,56.274162,-121.05373,1990-01-05,-19.0,-7.6,81,4.3,119,0.09,8.0,11.6,8.4,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,56.274162,-121.05373,2022-12-28,-15.4,-14.0,79,1.6,351,0.08,6.0,5.8,4.0,74
12050,56.274162,-121.05373,2022-12-29,-15.9,-13.4,89,0.0,2,0.06,0.0,7.3,4.6,85
12051,56.274162,-121.05373,2022-12-30,-15.3,-10.9,87,0.0,75,0.07,0.0,9.5,5.5,80
12052,56.274162,-121.05373,2022-12-31,-13.9,-11.2,88,0.0,220,0.07,0.0,4.8,2.6,86
12053,56.274162,-121.05373,2023-01-01,-9.4,-2.3,84,0.0,258,0.18,0.0,14.6,11.9,73

### Daten zusammenführen pro Provinz und Durchschnitt berechnen

In [4]:

# in Datetime umwandeln
for df in [British_Columbia_1, British_Columbia_2, British_Columbia_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [British_Columbia_1, British_Columbia_2, British_Columbia_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
British_Columbia_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

British_Columbia_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-3.766667,0.466667,86.000000,72.666667,1.400000,5.666667,9.166667,12.733333,219.000000,0.260000
1,1990-01-02,-10.066667,-5.633333,73.333333,57.333333,1.100000,5.000000,7.066667,10.566667,125.666667,0.233333
2,1990-01-03,-9.500000,-6.966667,79.000000,65.333333,4.433333,14.000000,8.366667,10.400000,111.666667,0.176667
3,1990-01-04,-9.166667,-6.366667,84.000000,75.666667,4.033333,12.000000,6.766667,9.633333,113.333333,0.176667
4,1990-01-05,-6.866667,-0.800000,83.666667,72.000000,2.666667,6.333333,10.233333,14.333333,147.666667,0.220000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-4.500000,-2.866667,86.666667,75.666667,1.900000,10.666667,4.933333,7.800000,290.333333,0.180000
12050,2022-12-29,-7.900000,-4.166667,88.000000,76.666667,0.000000,0.000000,6.833333,11.166667,142.333333,0.176667
12051,2022-12-30,-6.100000,-2.766667,87.000000,79.666667,2.200000,9.000000,7.900000,10.566667,171.333333,0.193333
12052,2022-12-31,-5.733333,-3.100000,89.000000,81.666667,1.633333,3.666667,5.100000,7.800000,208.333333,0.196667
12053,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

### Durschnitt pro Monat

In [5]:

British_Columbia_mean['time'] = pd.to_datetime(British_Columbia_mean['time'])

# Monats-Durchschnitt für alle Variablen
British_Columbia_monthly_mean = (
    British_Columbia_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

British_Columbia_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-7.217204,-3.096774,80.827957,67.301075,1.897849,5.365591,8.690323,12.411828,195.720430,0.305269
1,1990-02-01,-8.708333,-2.703571,74.023810,55.714286,1.233333,4.000000,8.808333,12.864286,190.511905,0.605714
2,1990-03-01,-0.410753,5.854839,70.774194,46.817204,0.783871,2.591398,7.102151,11.177419,198.150538,1.463763
3,1990-04-01,5.446667,11.931111,65.322222,38.933333,1.227778,3.522222,6.862222,11.044444,186.688889,2.393444
4,1990-05-01,10.031183,16.084946,69.774194,42.430108,2.725806,6.043011,6.849462,11.625806,201.365591,2.998065
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.718889,21.870000,62.866667,34.522222,0.834444,1.366667,7.303333,12.341111,226.355556,2.794667
393,2022-10-01,9.849462,15.419355,67.139785,42.569892,0.772043,1.978495,8.088172,13.237634,201.344086,1.592903
394,2022-11-01,-4.906667,-1.096667,75.155556,59.755556,1.555556,4.066667,8.901111,12.875556,193.388889,0.451000
395,2022-12-01,-12.351613,-8.421505,79.559140,68.365591,1.718280,5.344086,7.688172,11.604301,208.806452,0.193871
396,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

In [7]:
import os
#Datei speichern
output_path = "../data/cleaned_British_Columbia_monthly_mean.csv"


# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

British_Columbia_monthly_mean.to_csv(output_path, index=False)

### Alberta

In [6]:
#Fort McMurray Forest Zone
#→ 56.75, -111.45
import pandas as pd

pfad = "../data/import weather data/import data/Alberta/open-meteo-56.77N111.51W352m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,56.766254,-111.50943,1990-01-01,-8.0,-4.5,84,0.1,332,0.11,1.0,11.8,9.7,74
1,56.766254,-111.50943,1990-01-02,-17.1,-13.3,83,0.2,360,0.05,2.0,9.6,4.8,78
2,56.766254,-111.50943,1990-01-03,-24.8,-18.9,78,0.0,320,0.04,0.0,8.0,5.7,74
3,56.766254,-111.50943,1990-01-04,-28.7,-27.3,72,0.0,229,0.05,0.0,10.9,6.6,62
4,56.766254,-111.50943,1990-01-05,-29.8,-21.3,76,0.0,189,0.05,0.0,11.5,9.0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,56.766254,-111.50943,2022-12-28,-14.6,-13.1,74,0.8,113,0.11,6.0,11.7,7.4,71
12050,56.766254,-111.50943,2022-12-29,-16.0,-13.2,82,0.3,128,0.07,3.0,8.4,5.3,77
12051,56.766254,-111.50943,2022-12-30,-14.0,-9.4,85,0.0,150,0.07,0.0,9.2,4.9,80
12052,56.766254,-111.50943,2022-12-31,-9.2,-7.0,88,0.5,127,0.08,5.0,5.8,4.0,82
12053,56.766254,-111.50943,2023-01-01,-9.7,-6.5,85,0.0,226,0.11,0.0,11.2,8.7,78

In [7]:
#Slave Lake Wildland Area
#→ 55.28, -114.77

pfad = "../data/import weather data/import data/Alberta/open-meteo-55.29N114.76W585m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,55.28998,-114.75903,1990-01-01,-3.6,-2.1,85,1.7,295,0.20,8.0,14.4,9.8,74
1,55.28998,-114.75903,1990-01-02,-8.2,-4.1,76,0.2,330,0.20,1.0,11.9,9.1,67
2,55.28998,-114.75903,1990-01-03,-14.6,-10.4,72,3.8,16,0.17,16.0,13.6,10.0,63
3,55.28998,-114.75903,1990-01-04,-17.1,-15.5,72,1.4,76,0.12,8.0,10.2,7.6,64
4,55.28998,-114.75903,1990-01-05,-16.6,-8.2,82,1.2,136,0.13,5.0,17.1,11.3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,55.28998,-114.75903,2022-12-28,-11.0,-10.0,81,4.9,116,0.15,18.0,19.0,11.2,76
12050,55.28998,-114.75903,2022-12-29,-15.2,-13.1,81,0.0,99,0.11,0.0,11.5,8.2,70
12051,55.28998,-114.75903,2022-12-30,-11.8,-8.8,88,0.0,105,0.10,0.0,15.6,13.1,83
12052,55.28998,-114.75903,2022-12-31,-12.2,-9.6,86,0.0,107,0.09,0.0,14.2,9.2,78
12053,55.28998,-114.75903,2023-01-01,-8.7,-3.2,83,0.0,311,0.18,0.0,16.1,10.8,75

In [8]:
#Rocky Mountain House Forest Belt
#→ 52.37, -115.10

pfad = "../data/import weather data/import data/Alberta/open-meteo-52.34N115.17W1007m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.337433,-115.16666,1990-01-01,-2.7,0.2,69,0.0,253,0.46,0.0,15.8,9.1,58
1,52.337433,-115.16666,1990-01-02,-5.0,-2.6,87,1.2,355,0.21,10.0,12.3,7.7,66
2,52.337433,-115.16666,1990-01-03,-8.1,-5.8,74,0.0,262,0.26,0.0,11.7,8.1,60
3,52.337433,-115.16666,1990-01-04,-10.4,-6.7,83,0.9,154,0.16,5.0,13.6,8.5,76
4,52.337433,-115.16666,1990-01-05,-10.1,1.6,81,0.1,183,0.29,1.0,11.8,8.7,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.337433,-115.16666,2022-12-28,-4.6,0.9,91,2.0,357,0.16,10.0,9.8,6.2,77
12050,52.337433,-115.16666,2022-12-29,-6.4,-0.7,83,0.2,222,0.27,2.0,9.2,5.8,56
12051,52.337433,-115.16666,2022-12-30,-5.2,0.4,73,0.0,223,0.32,0.0,12.2,7.8,55
12052,52.337433,-115.16666,2022-12-31,-3.5,1.2,77,0.0,265,0.36,0.0,12.0,8.2,64
12053,52.337433,-115.16666,2023-01-01,-2.1,2.7,76,1.0,257,0.34,5.0,12.0,8.1,52

### Durschnitt pro Provinz

In [14]:

# in Datetime umwandeln
for df in [Alberta_1, Alberta_2, Alberta_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Alberta_1, Alberta_2, Alberta_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Alberta_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Alberta_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-4.766667,-2.133333,79.333333,68.666667,0.600000,3.000000,9.533333,14.000000,293.333333,0.256667
1,1990-01-02,-10.100000,-6.666667,82.000000,70.333333,0.533333,4.333333,7.200000,11.266667,348.333333,0.153333
2,1990-01-03,-15.833333,-11.700000,74.666667,65.666667,1.266667,5.333333,7.933333,11.100000,199.333333,0.156667
3,1990-01-04,-18.733333,-16.500000,75.666667,67.333333,0.766667,4.333333,7.566667,11.566667,153.000000,0.110000
4,1990-01-05,-18.833333,-9.300000,79.666667,71.000000,0.433333,2.000000,9.666667,13.466667,169.333333,0.156667
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-10.066667,-7.400000,82.000000,74.666667,2.566667,11.333333,8.266667,13.500000,195.333333,0.140000
12050,2022-12-29,-12.533333,-9.000000,82.000000,67.666667,0.166667,1.666667,6.433333,9.700000,149.666667,0.150000
12051,2022-12-30,-10.333333,-5.933333,82.000000,72.666667,0.000000,0.000000,8.600000,12.333333,159.333333,0.163333
12052,2022-12-31,-8.300000,-5.133333,83.666667,74.666667,0.166667,1.666667,7.133333,10.666667,166.333333,0.176667
12053,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000

### Durschnitt pro Monat

In [15]:

Alberta_mean['time'] = pd.to_datetime(Alberta_mean['time'])

# Monats-Durchschnitt für alle Variablen
Alberta_monthly_mean = (
    Alberta_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Alberta_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-11.569892,-6.860215,76.344086,64.795699,0.592473,2.505376,10.409677,15.327957,223.365591,0.289140
1,1990-02-01,-13.560714,-6.180952,71.392857,52.857143,0.458333,1.797619,10.897619,16.297619,206.761905,0.532976
2,1990-03-01,-2.176344,5.023656,67.838710,42.827957,0.488172,1.838710,10.551613,15.489247,229.709677,1.406667
3,1990-04-01,2.753333,9.282222,64.888889,40.122222,1.252222,3.288889,10.631111,16.352222,208.500000,2.221222
4,1990-05-01,9.982796,16.177419,65.139785,39.204301,1.895699,3.483871,10.335484,16.073118,186.462366,3.430645
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.074444,21.204444,64.833333,39.666667,0.855556,2.000000,10.297778,15.964444,225.666667,2.744333
393,2022-10-01,8.090323,13.873118,65.150538,43.483871,0.744086,1.806452,11.341935,18.224731,219.032258,1.712258
394,2022-11-01,-5.663333,-1.366667,69.633333,53.433333,0.964444,4.277778,12.106667,17.871111,241.311111,0.541778
395,2022-12-01,-16.086022,-11.305376,75.344086,65.043011,0.983871,4.387097,10.149462,15.201075,215.591398,0.184946
396,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000

### Jahr und Monat in verschiedene Columns

In [16]:
# sicherstellen, dass time datetime ist
Alberta_monthly_mean['time'] = pd.to_datetime(Alberta_monthly_mean['time'])

# Jahr und Monat extrahieren
Alberta_monthly_mean['Year'] = Alberta_monthly_mean['time'].dt.year
Alberta_monthly_mean['Month'] = Alberta_monthly_mean['time'].dt.month
Alberta_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-11.569892,-6.860215,76.344086,64.795699,0.592473,2.505376,10.409677,15.327957,223.365591,0.289140,1990,1
1,1990-02-01,-13.560714,-6.180952,71.392857,52.857143,0.458333,1.797619,10.897619,16.297619,206.761905,0.532976,1990,2
2,1990-03-01,-2.176344,5.023656,67.838710,42.827957,0.488172,1.838710,10.551613,15.489247,229.709677,1.406667,1990,3
3,1990-04-01,2.753333,9.282222,64.888889,40.122222,1.252222,3.288889,10.631111,16.352222,208.500000,2.221222,1990,4
4,1990-05-01,9.982796,16.177419,65.139785,39.204301,1.895699,3.483871,10.335484,16.073118,186.462366,3.430645,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.074444,21.204444,64.833333,39.666667,0.855556,2.000000,10.297778,15.964444,225.666667,2.744333,2022,9
393,2022-10-01,8.090323,13.873118,65.150538,43.483871,0.744086,1.806452,11.341935,18.224731,219.032258,1.712258,2022,10
394,2022-11-01,-5.663333,-1.366667,69.633333,53.433333,0.964444,4.277778,12.106667,17.871111,241.311111,0.541778,2022,11
395,2022-12-01,-16.086022,-11.305376,75.344086,65.043011,0.983871,4.387097,10.149462,15.201075,215.591398,0.184946,2022,12
396,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000,2023,1

In [18]:
import os
#Datei speichern
output_path = "../data/cleaned_Alberta_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Alberta_monthly_mean.to_csv(output_path, index=False)

## Quebec

In [20]:
#Chibougamau / Eeyou Istchee Boreal Forest
#→ 49.90,-74.38

pfad = "../data/import weather data/import data/Quebec/open-meteo-49.88N74.35W429m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,49.876976,-74.34784,1990-01-01,-12.8,-8.1,81,4.7,300,0.20,15.0,25.4,17.1,69
1,49.876976,-74.34784,1990-01-02,-15.9,-6.4,81,2.3,243,0.21,13.0,23.7,16.6,75
2,49.876976,-74.34784,1990-01-03,-12.0,-6.0,78,0.9,283,0.26,5.0,20.6,13.0,68
3,49.876976,-74.34784,1990-01-04,-4.2,-1.0,86,2.6,223,0.28,16.0,19.1,16.7,78
4,49.876976,-74.34784,1990-01-05,-18.6,-9.0,75,0.0,276,0.20,0.0,20.1,14.2,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,49.876976,-74.34784,2022-12-28,-13.7,-8.6,80,1.5,167,0.19,9.0,12.6,9.3,77
12050,49.876976,-74.34784,2022-12-29,-8.1,-3.6,88,12.6,130,0.16,17.0,22.3,16.8,86
12051,49.876976,-74.34784,2022-12-30,1.7,4.4,91,1.1,197,0.23,8.0,23.6,17.2,88
12052,49.876976,-74.34784,2022-12-31,-0.3,4.2,89,0.2,259,0.21,2.0,23.0,14.2,84
12053,49.876976,-74.34784,2023-01-01,-5.8,-3.4,86,0.0,322,0.20,0.0,12.5,9.5,78

In [23]:
#La Grande / Nord-du-Québec Feuerzonen
#→ 53.60, -76.10

pfad = "../data/import weather data/import data/Quebec/open-meteo-53.60N76.03W237m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,53.60281,-76.034485,1990-01-01,-18.5,-13.7,79,1.2,298,0.11,7.0,21.9,15.3,72
1,53.60281,-76.034485,1990-01-02,-21.9,-16.0,78,1.7,195,0.11,10.0,16.2,11.3,76
2,53.60281,-76.034485,1990-01-03,-22.7,-17.3,78,0.1,254,0.09,1.0,15.1,10.3,71
3,53.60281,-76.034485,1990-01-04,-16.4,-8.5,77,2.9,219,0.21,9.0,29.6,23.4,68
4,53.60281,-76.034485,1990-01-05,-27.5,-23.1,74,0.0,255,0.09,0.0,19.8,16.3,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,53.60281,-76.034485,2022-12-28,-18.4,-17.0,79,0.7,202,0.13,7.0,17.3,9.8,74
12050,53.60281,-76.034485,2022-12-29,-15.2,-9.1,78,0.8,119,0.21,5.0,21.4,16.0,71
12051,53.60281,-76.034485,2022-12-30,-4.0,0.5,92,6.4,156,0.11,15.0,17.5,14.2,83
12052,53.60281,-76.034485,2022-12-31,-6.3,-0.8,85,2.7,249,0.21,23.0,23.1,17.8,78
12053,53.60281,-76.034485,2023-01-01,-11.3,-9.6,84,0.4,245,0.12,4.0,10.8,8.0,80

In [24]:
#Mauricie Boreal Forest Belt
#→ 47.00, -72.80

pfad = "../data/import weather data/import data/Quebec/open-meteo-46.99N72.76W381m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,46.994724,-72.759766,1990-01-01,-4.3,0.6,85,8.0,279,0.35,19.0,25.5,17.3,64
1,46.994724,-72.759766,1990-01-02,-12.7,-4.4,76,0.0,259,0.32,0.0,22.7,14.3,69
2,46.994724,-72.759766,1990-01-03,-2.9,-1.1,81,0.0,245,0.44,0.0,14.0,10.3,68
3,46.994724,-72.759766,1990-01-04,-1.6,0.4,93,7.5,179,0.19,9.0,13.7,12.5,88
4,46.994724,-72.759766,1990-01-05,-7.3,0.2,72,3.1,305,0.47,3.0,21.3,13.5,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,46.994724,-72.759766,2022-12-28,-11.8,-6.5,86,3.5,163,0.14,15.0,10.7,8.9,78
12050,46.994724,-72.759766,2022-12-29,-4.4,-1.5,92,4.3,138,0.19,13.0,16.3,10.3,83
12051,46.994724,-72.759766,2022-12-30,2.1,5.2,90,0.3,179,0.29,3.0,12.8,11.0,83
12052,46.994724,-72.759766,2022-12-31,2.7,4.4,93,9.1,177,0.23,19.0,11.8,6.6,78
12053,46.994724,-72.759766,2023-01-01,-0.3,1.2,89,6.0,345,0.34,15.0,15.4,10.7,71

### Durschnitt pro Provinz

In [25]:

# in Datetime umwandeln
for df in [Quebec_1, Quebec_2, Quebec_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Quebec_1, Quebec_2, Quebec_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Quebec_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Quebec_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-11.866667,-7.066667,81.666667,68.333333,4.633333,13.666667,16.566667,24.266667,292.333333,0.220000
1,1990-01-02,-16.833333,-8.933333,78.333333,73.333333,1.333333,7.666667,14.066667,20.866667,232.333333,0.213333
2,1990-01-03,-12.533333,-8.133333,79.000000,69.000000,0.333333,2.000000,11.200000,16.566667,260.666667,0.263333
3,1990-01-04,-7.400000,-3.033333,85.333333,78.000000,4.333333,11.333333,17.533333,20.800000,207.000000,0.226667
4,1990-01-05,-17.800000,-10.633333,73.666667,62.000000,1.033333,1.000000,14.666667,20.400000,278.666667,0.253333
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-14.633333,-10.700000,81.666667,76.333333,1.900000,10.333333,9.333333,13.533333,177.333333,0.153333
12050,2022-12-29,-9.233333,-4.733333,86.000000,80.000000,5.900000,11.666667,14.366667,20.000000,129.000000,0.186667
12051,2022-12-30,-0.066667,3.366667,91.000000,84.666667,2.600000,8.666667,14.133333,17.966667,177.333333,0.210000
12052,2022-12-31,-1.300000,2.600000,89.000000,80.000000,4.000000,14.666667,12.866667,19.300000,228.333333,0.216667
12053,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000

### Durchschnitt pro Monat

In [26]:

Quebec_mean['time'] = pd.to_datetime(Quebec_mean['time'])

# Monats-Durchschnitt für alle Variablen
Quebec_monthly_mean = (
    Quebec_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Quebec_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000

In [27]:
# Jahr und Monat extrahieren
Quebec_monthly_mean['Year'] = Quebec_monthly_mean['time'].dt.year
Quebec_monthly_mean['Month'] = Quebec_monthly_mean['time'].dt.month
Quebec_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376,1990,1
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310,1990,2
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462,1990,3
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111,1990,4
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000,2022,9
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892,2022,10
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556,2022,11
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849,2022,12
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000,2023,1

In [28]:
import os
#Datei speichern
output_path = "../data/cleaned_Quebec_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Quebec_monthly_mean.to_csv(output_path, index=False)

## Ontario

In [29]:
#Red Lake – eine der aktivsten Brandregionen:
#→ 51.02, -93.82

pfad = "../data/import weather data/import data/Ontario/open-meteo-51.00N93.86W356m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,51.001755,-93.864044,1990-01-01,-12.7,-8.7,80,0.0,208,0.20,0.0,27.4,14.3,71
1,51.001755,-93.864044,1990-01-02,-6.2,-4.3,83,0.0,278,0.28,0.0,21.8,14.8,74
2,51.001755,-93.864044,1990-01-03,-10.5,-7.7,85,3.7,25,0.16,9.0,20.2,11.6,76
3,51.001755,-93.864044,1990-01-04,-17.7,-13.4,77,0.1,289,0.17,1.0,18.7,12.6,67
4,51.001755,-93.864044,1990-01-05,-22.5,-21.0,76,0.0,272,0.13,0.0,10.9,8.8,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,51.001755,-93.864044,2022-12-28,-11.2,-6.5,83,0.8,95,0.22,5.0,17.3,15.5,80
12050,51.001755,-93.864044,2022-12-29,-5.9,-4.7,89,0.9,109,0.15,5.0,14.1,7.8,86
12051,51.001755,-93.864044,2022-12-30,-10.9,-5.0,82,2.3,265,0.19,10.0,15.3,12.1,71
12052,51.001755,-93.864044,2022-12-31,-15.2,-11.7,80,0.0,162,0.18,0.0,12.3,8.5,71
12053,51.001755,-93.864044,2023-01-01,-10.2,-7.8,86,0.0,74,0.14,0.0,8.4,5.0,82

In [30]:
#Sioux Lookout Boreal Forest
#→ 50.10, -91.90

pfad = "../data/import weather data/import data/Ontario/open-meteo-50.09N91.89W371m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,50.08787,-91.88812,1990-01-01,-11.8,-8.4,80,0.0,226,0.22,0.0,25.5,13.0,70
1,50.08787,-91.88812,1990-01-02,-3.5,-1.5,82,0.0,257,0.36,0.0,24.3,15.8,72
2,50.08787,-91.88812,1990-01-03,-4.7,-2.6,88,3.0,107,0.23,9.0,21.3,12.8,80
3,50.08787,-91.88812,1990-01-04,-14.1,-7.7,78,0.1,284,0.22,1.0,20.5,12.9,68
4,50.08787,-91.88812,1990-01-05,-20.6,-18.3,77,0.0,282,0.14,0.0,11.5,7.2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,50.08787,-91.88812,2022-12-28,-8.4,-4.1,85,0.4,95,0.19,3.0,16.2,12.1,80
12050,50.08787,-91.88812,2022-12-29,-4.3,-2.8,90,1.2,102,0.17,1.0,15.9,7.6,85
12051,50.08787,-91.88812,2022-12-30,-6.8,-3.2,86,1.6,268,0.20,11.0,15.9,11.6,75
12052,50.08787,-91.88812,2022-12-31,-13.8,-10.9,83,0.0,170,0.18,0.0,12.0,7.9,75
12053,50.08787,-91.88812,2023-01-01,-8.2,-6.5,86,0.3,37,0.18,3.0,8.3,5.9,80

In [31]:
#Temagami Forest Region
#→ 47.06, -80.06

pfad = "../data/import weather data/import data/Ontario/open-meteo-47.07N80.05W347m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,47.065025,-80.0488,1990-01-01,-11.5,-10.6,77,2.8,318,0.32,11.0,16.9,13.9,65
1,47.065025,-80.0488,1990-01-02,-7.3,-2.5,82,0.0,226,0.41,0.0,26.0,19.5,75
2,47.065025,-80.0488,1990-01-03,-4.6,-1.2,91,0.0,202,0.26,0.0,20.0,12.7,82
3,47.065025,-80.0488,1990-01-04,-0.4,0.6,91,5.3,243,0.23,10.0,19.5,13.1,82
4,47.065025,-80.0488,1990-01-05,-8.5,-4.0,80,0.0,287,0.27,0.0,13.4,8.8,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,47.065025,-80.0488,2022-12-28,-3.5,-0.7,89,7.9,204,0.22,16.0,17.9,13.2,85
12050,47.065025,-80.0488,2022-12-29,1.6,4.1,85,0.8,195,0.50,2.0,18.6,16.5,78
12051,47.065025,-80.0488,2022-12-30,4.3,5.6,96,1.2,209,0.23,9.0,22.1,17.8,87
12052,47.065025,-80.0488,2022-12-31,0.2,3.4,91,0.0,278,0.26,0.0,16.3,7.1,81
12053,47.065025,-80.0488,2023-01-01,-1.6,-0.7,88,0.0,312,0.34,0.0,10.5,7.5,74

### Durschnitt pro Provinz

In [32]:

# in Datetime umwandeln
for df in [Ontario_1, Ontario_2, Ontario_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Ontario_1, Ontario_2, Ontario_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Ontario_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Ontario_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-12.000000,-9.233333,79.000000,68.666667,0.933333,3.666667,13.733333,23.266667,250.666667,0.246667
1,1990-01-02,-5.666667,-2.766667,82.333333,73.666667,0.000000,0.000000,16.700000,24.033333,253.666667,0.350000
2,1990-01-03,-6.600000,-3.833333,88.000000,79.333333,2.233333,6.000000,12.366667,20.500000,111.333333,0.216667
3,1990-01-04,-10.733333,-6.833333,82.000000,72.333333,1.833333,4.000000,12.866667,19.566667,272.000000,0.206667
4,1990-01-05,-17.200000,-14.433333,77.666667,66.000000,0.000000,0.000000,8.266667,11.933333,280.333333,0.180000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-7.700000,-3.766667,85.666667,81.666667,3.033333,8.000000,13.600000,17.133333,131.333333,0.210000
12050,2022-12-29,-2.866667,-1.133333,88.000000,83.000000,0.966667,2.666667,10.633333,16.200000,135.333333,0.273333
12051,2022-12-30,-4.466667,-0.866667,88.000000,77.666667,1.700000,10.000000,13.833333,17.766667,247.333333,0.206667
12052,2022-12-31,-9.600000,-6.400000,84.666667,75.666667,0.000000,0.000000,7.833333,13.533333,203.333333,0.206667
12053,2023-01-01,-6.666667,-5.000000,86.666667,78.666667,0.100000,1.000000,6.133333,9.066667,141.000000,0.220000

### Durchschnitt Monat

In [33]:
Ontario_mean['time'] = pd.to_datetime(Ontario_mean['time'])

# Monats-Durchschnitt für alle Variablen
Ontario_monthly_mean = (
    Quebec_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Ontario_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000

In [34]:
# Jahr und Monat extrahieren
Ontario_monthly_mean['Year'] = Ontario_monthly_mean['time'].dt.year
Ontario_monthly_mean['Month'] = Ontario_monthly_mean['time'].dt.month
Ontario_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376,1990,1
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310,1990,2
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462,1990,3
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111,1990,4
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000,2022,9
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892,2022,10
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556,2022,11
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849,2022,12
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000,2023,1

In [35]:
import os

#Datei speichern
output_path = "../data/cleaned_Ontario_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Ontario_monthly_mean.to_csv(output_path, index=False)

## Saskatchewan

In [36]:
#Prince Albert National Park
#→ 53.96, -106.22

pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-53.95N106.19W532m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,53.954304,-106.18956,1990-01-01,-8.4,-4.6,86,0.1,242,0.18,1.0,20.1,14.9,79
1,53.954304,-106.18956,1990-01-02,-11.3,-5.2,83,0.0,4,0.11,0.0,13.4,7.9,76
2,53.954304,-106.18956,1990-01-03,-15.9,-14.1,82,2.2,324,0.09,10.0,13.4,6.6,72
3,53.954304,-106.18956,1990-01-04,-23.6,-19.3,77,0.0,287,0.08,0.0,13.3,7.6,66
4,53.954304,-106.18956,1990-01-05,-23.6,-21.3,77,0.0,250,0.08,0.0,11.7,8.2,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,53.954304,-106.18956,2022-12-28,-16.8,-15.7,78,4.4,63,0.12,24.0,12.8,10.7,73
12050,53.954304,-106.18956,2022-12-29,-18.3,-17.6,76,0.2,335,0.09,2.0,9.4,6.0,69
12051,53.954304,-106.18956,2022-12-30,-15.9,-12.6,81,0.1,176,0.12,1.0,11.6,8.4,75
12052,53.954304,-106.18956,2022-12-31,-12.9,-11.4,88,0.0,104,0.09,0.0,11.6,5.8,83
12053,53.954304,-106.18956,2023-01-01,-10.9,-8.1,87,0.0,269,0.11,0.0,10.2,6.3,81

In [37]:
#La Ronge borealer Wald
# 55.10, -105.30

pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-55.08N105.45W370m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,55.079086,-105.4491,1990-01-01,-11.2,-9.1,82,0.0,242,0.18,0.0,19.8,14.4,74
1,55.079086,-105.4491,1990-01-02,-13.8,-9.7,79,0.0,353,0.11,0.0,14.9,8.1,74
2,55.079086,-105.4491,1990-01-03,-17.8,-16.0,80,0.8,313,0.08,6.0,15.1,6.7,72
3,55.079086,-105.4491,1990-01-04,-25.0,-20.9,75,0.0,280,0.09,0.0,15.6,10.3,70
4,55.079086,-105.4491,1990-01-05,-26.6,-22.2,74,0.0,255,0.08,0.0,12.5,9.5,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,55.079086,-105.4491,2022-12-28,-17.5,-15.9,77,3.4,79,0.17,23.0,20.8,17.8,74
12050,55.079086,-105.4491,2022-12-29,-19.2,-18.7,74,0.5,2,0.08,5.0,10.7,6.2,72
12051,55.079086,-105.4491,2022-12-30,-19.4,-15.7,79,0.0,116,0.09,0.0,11.0,6.1,72
12052,55.079086,-105.4491,2022-12-31,-13.7,-11.4,83,0.0,131,0.08,0.0,8.9,4.4,73
12053,55.079086,-105.4491,2023-01-01,-11.7,-8.9,85,0.0,249,0.10,0.0,7.3,5.3,77

In [ ]:
#Meadow Lake Provincial Park
#→ 54.14, -108.44
pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-53.95N106.19W532m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_1

### Durchschnitt pro Provinz

In [ ]:
in Datetime umwandeln
for df in [Ontario_1, Ontario_2, Ontario_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Ontario_1, Ontario_2, Ontario_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Ontario_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Ontario_mean

### Durchschnitt pro Monat

In [ ]:
Ontario_mean['time'] = pd.to_datetime(Ontario_mean['time'])

# Monats-Durchschnitt für alle Variablen
Ontario_monthly_mean = (
    Quebec_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Ontario_monthly_mean

In [ ]:
# Jahr und Monat extrahieren
Ontario_monthly_mean['Year'] = Ontario_monthly_mean['time'].dt.year
Ontario_monthly_mean['Month'] = Ontario_monthly_mean['time'].dt.month
# Spalte time entfernen
Ontario_monthly_mean.drop(columns=["time"])
Ontario_monthly_mean

In [ ]:
import os

#Datei speichern
output_path = "../data/cleaned_Ontario_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Ontario_monthly_mean.to_csv(output_path, index=False)