### Wetter Daten laden (Von 1990 bis 2023)

### British Columbia (BC)

In [1]:
#Cariboo Region (Williams Lake Area)
#→ 52.15, -122.15

import pandas as pd

pfad = "../data/import weather data/import data/British Columbia/open-meteo-52.55N122.18W978m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.54833,-122.17876,1990-01-01,-4.5,-0.7,88,0.6,135,0.22,2.0,16.5,9.4,74
1,52.54833,-122.17876,1990-01-02,-12.9,-6.4,80,1.6,121,0.13,5.0,11.5,6.8,69
2,52.54833,-122.17876,1990-01-03,-7.0,-4.6,85,9.5,133,0.17,24.0,13.5,12.2,79
3,52.54833,-122.17876,1990-01-04,-6.8,-4.0,88,5.1,129,0.19,11.0,15.0,10.3,80
4,52.54833,-122.17876,1990-01-05,-3.4,1.2,83,2.4,136,0.38,7.0,23.6,16.3,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.54833,-122.17876,2022-12-28,-1.6,0.3,93,1.5,307,0.21,8.0,10.8,5.9,73
12050,52.54833,-122.17876,2022-12-29,-5.7,-2.5,89,0.0,137,0.21,0.0,17.4,9.7,72
12051,52.54833,-122.17876,2022-12-30,-3.5,-0.7,87,2.0,125,0.23,11.0,16.0,13.8,79
12052,52.54833,-122.17876,2022-12-31,-3.6,-2.2,91,4.1,128,0.16,7.0,12.1,7.8,86
12053,52.54833,-122.17876,2023-01-01,-6.1,-2.7,91,0.0,154,0.19,0.0,7.8,5.0,78

In [2]:
#Okanagan – feueranfälligste Region in BC
#→ 49.80, -119.60

pfad = "../data/import weather data/import data/British Columbia/open-meteo-49.81N119.69W339m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,49.806675,-119.6875,1990-01-01,0.2,3.0,94,0.3,170,0.34,3.0,9.3,7.6,78
1,49.806675,-119.6875,1990-01-02,-0.2,2.3,78,0.8,244,0.41,5.0,8.3,6.8,50
2,49.806675,-119.6875,1990-01-03,-1.8,1.1,84,0.9,188,0.25,5.0,7.6,6.0,53
3,49.806675,-119.6875,1990-01-04,-0.5,3.6,87,4.0,166,0.28,14.0,7.3,5.6,80
4,49.806675,-119.6875,1990-01-05,1.8,4.0,87,1.3,188,0.19,4.0,7.8,6.0,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,49.806675,-119.6875,2022-12-28,3.5,5.1,88,2.6,213,0.25,18.0,6.8,4.9,80
12050,49.806675,-119.6875,2022-12-29,-2.1,3.4,86,0.0,288,0.26,0.0,8.8,6.2,73
12051,49.806675,-119.6875,2022-12-30,0.5,3.3,87,4.6,314,0.28,16.0,6.2,4.4,80
12052,49.806675,-119.6875,2022-12-31,0.3,4.1,88,0.8,277,0.36,4.0,6.5,4.9,73
12053,49.806675,-119.6875,2023-01-01,1.7,4.1,82,2.0,217,0.40,6.0,7.0,5.0,66

In [3]:
#Peace River Forest / Fort St. John Hinterland
#→ 56.30, -121.00


pfad = "../data/import weather data/import data/British Columbia/open-meteo-56.27N121.05W789m-2.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
British_Columbia_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

British_Columbia_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,56.274162,-121.05373,1990-01-01,-7.0,-0.9,76,3.3,352,0.22,12.0,12.4,10.5,66
1,56.274162,-121.05373,1990-01-02,-17.1,-12.8,62,0.9,12,0.16,5.0,11.9,7.6,53
2,56.274162,-121.05373,1990-01-03,-19.7,-17.4,68,2.9,14,0.11,13.0,10.1,6.9,64
3,56.274162,-121.05373,1990-01-04,-20.2,-18.7,77,3.0,45,0.06,11.0,6.6,4.4,67
4,56.274162,-121.05373,1990-01-05,-19.0,-7.6,81,4.3,119,0.09,8.0,11.6,8.4,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,56.274162,-121.05373,2022-12-28,-15.4,-14.0,79,1.6,351,0.08,6.0,5.8,4.0,74
12050,56.274162,-121.05373,2022-12-29,-15.9,-13.4,89,0.0,2,0.06,0.0,7.3,4.6,85
12051,56.274162,-121.05373,2022-12-30,-15.3,-10.9,87,0.0,75,0.07,0.0,9.5,5.5,80
12052,56.274162,-121.05373,2022-12-31,-13.9,-11.2,88,0.0,220,0.07,0.0,4.8,2.6,86
12053,56.274162,-121.05373,2023-01-01,-9.4,-2.3,84,0.0,258,0.18,0.0,14.6,11.9,73

### Daten zusammenführen pro Provinz und Durchschnitt berechnen

In [4]:

# in Datetime umwandeln
for df in [British_Columbia_1, British_Columbia_2, British_Columbia_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [British_Columbia_1, British_Columbia_2, British_Columbia_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
British_Columbia_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

British_Columbia_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-3.766667,0.466667,86.000000,72.666667,1.400000,5.666667,9.166667,12.733333,219.000000,0.260000
1,1990-01-02,-10.066667,-5.633333,73.333333,57.333333,1.100000,5.000000,7.066667,10.566667,125.666667,0.233333
2,1990-01-03,-9.500000,-6.966667,79.000000,65.333333,4.433333,14.000000,8.366667,10.400000,111.666667,0.176667
3,1990-01-04,-9.166667,-6.366667,84.000000,75.666667,4.033333,12.000000,6.766667,9.633333,113.333333,0.176667
4,1990-01-05,-6.866667,-0.800000,83.666667,72.000000,2.666667,6.333333,10.233333,14.333333,147.666667,0.220000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-4.500000,-2.866667,86.666667,75.666667,1.900000,10.666667,4.933333,7.800000,290.333333,0.180000
12050,2022-12-29,-7.900000,-4.166667,88.000000,76.666667,0.000000,0.000000,6.833333,11.166667,142.333333,0.176667
12051,2022-12-30,-6.100000,-2.766667,87.000000,79.666667,2.200000,9.000000,7.900000,10.566667,171.333333,0.193333
12052,2022-12-31,-5.733333,-3.100000,89.000000,81.666667,1.633333,3.666667,5.100000,7.800000,208.333333,0.196667
12053,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

### Durschnitt pro Monat

In [5]:

British_Columbia_mean['time'] = pd.to_datetime(British_Columbia_mean['time'])

# Monats-Durchschnitt für alle Variablen
British_Columbia_monthly_mean = (
    British_Columbia_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

British_Columbia_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-7.217204,-3.096774,80.827957,67.301075,1.897849,5.365591,8.690323,12.411828,195.720430,0.305269
1,1990-02-01,-8.708333,-2.703571,74.023810,55.714286,1.233333,4.000000,8.808333,12.864286,190.511905,0.605714
2,1990-03-01,-0.410753,5.854839,70.774194,46.817204,0.783871,2.591398,7.102151,11.177419,198.150538,1.463763
3,1990-04-01,5.446667,11.931111,65.322222,38.933333,1.227778,3.522222,6.862222,11.044444,186.688889,2.393444
4,1990-05-01,10.031183,16.084946,69.774194,42.430108,2.725806,6.043011,6.849462,11.625806,201.365591,2.998065
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.718889,21.870000,62.866667,34.522222,0.834444,1.366667,7.303333,12.341111,226.355556,2.794667
393,2022-10-01,9.849462,15.419355,67.139785,42.569892,0.772043,1.978495,8.088172,13.237634,201.344086,1.592903
394,2022-11-01,-4.906667,-1.096667,75.155556,59.755556,1.555556,4.066667,8.901111,12.875556,193.388889,0.451000
395,2022-12-01,-12.351613,-8.421505,79.559140,68.365591,1.718280,5.344086,7.688172,11.604301,208.806452,0.193871
396,2023-01-01,-4.600000,-0.300000,85.666667,72.333333,0.666667,2.000000,7.300000,9.800000,209.666667,0.256667

In [7]:
import os
#Datei speichern
output_path = "../data/cleaned_British_Columbia_monthly_mean.csv"


# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

British_Columbia_monthly_mean.to_csv(output_path, index=False)

### Alberta

In [6]:
#Fort McMurray Forest Zone
#→ 56.75, -111.45
import pandas as pd

pfad = "../data/import weather data/import data/Alberta/open-meteo-56.77N111.51W352m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,56.766254,-111.50943,1990-01-01,-8.0,-4.5,84,0.1,332,0.11,1.0,11.8,9.7,74
1,56.766254,-111.50943,1990-01-02,-17.1,-13.3,83,0.2,360,0.05,2.0,9.6,4.8,78
2,56.766254,-111.50943,1990-01-03,-24.8,-18.9,78,0.0,320,0.04,0.0,8.0,5.7,74
3,56.766254,-111.50943,1990-01-04,-28.7,-27.3,72,0.0,229,0.05,0.0,10.9,6.6,62
4,56.766254,-111.50943,1990-01-05,-29.8,-21.3,76,0.0,189,0.05,0.0,11.5,9.0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,56.766254,-111.50943,2022-12-28,-14.6,-13.1,74,0.8,113,0.11,6.0,11.7,7.4,71
12050,56.766254,-111.50943,2022-12-29,-16.0,-13.2,82,0.3,128,0.07,3.0,8.4,5.3,77
12051,56.766254,-111.50943,2022-12-30,-14.0,-9.4,85,0.0,150,0.07,0.0,9.2,4.9,80
12052,56.766254,-111.50943,2022-12-31,-9.2,-7.0,88,0.5,127,0.08,5.0,5.8,4.0,82
12053,56.766254,-111.50943,2023-01-01,-9.7,-6.5,85,0.0,226,0.11,0.0,11.2,8.7,78

In [7]:
#Slave Lake Wildland Area
#→ 55.28, -114.77

pfad = "../data/import weather data/import data/Alberta/open-meteo-55.29N114.76W585m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,55.28998,-114.75903,1990-01-01,-3.6,-2.1,85,1.7,295,0.20,8.0,14.4,9.8,74
1,55.28998,-114.75903,1990-01-02,-8.2,-4.1,76,0.2,330,0.20,1.0,11.9,9.1,67
2,55.28998,-114.75903,1990-01-03,-14.6,-10.4,72,3.8,16,0.17,16.0,13.6,10.0,63
3,55.28998,-114.75903,1990-01-04,-17.1,-15.5,72,1.4,76,0.12,8.0,10.2,7.6,64
4,55.28998,-114.75903,1990-01-05,-16.6,-8.2,82,1.2,136,0.13,5.0,17.1,11.3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,55.28998,-114.75903,2022-12-28,-11.0,-10.0,81,4.9,116,0.15,18.0,19.0,11.2,76
12050,55.28998,-114.75903,2022-12-29,-15.2,-13.1,81,0.0,99,0.11,0.0,11.5,8.2,70
12051,55.28998,-114.75903,2022-12-30,-11.8,-8.8,88,0.0,105,0.10,0.0,15.6,13.1,83
12052,55.28998,-114.75903,2022-12-31,-12.2,-9.6,86,0.0,107,0.09,0.0,14.2,9.2,78
12053,55.28998,-114.75903,2023-01-01,-8.7,-3.2,83,0.0,311,0.18,0.0,16.1,10.8,75

In [8]:
#Rocky Mountain House Forest Belt
#→ 52.37, -115.10

pfad = "../data/import weather data/import data/Alberta/open-meteo-52.34N115.17W1007m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Alberta_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Alberta_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.337433,-115.16666,1990-01-01,-2.7,0.2,69,0.0,253,0.46,0.0,15.8,9.1,58
1,52.337433,-115.16666,1990-01-02,-5.0,-2.6,87,1.2,355,0.21,10.0,12.3,7.7,66
2,52.337433,-115.16666,1990-01-03,-8.1,-5.8,74,0.0,262,0.26,0.0,11.7,8.1,60
3,52.337433,-115.16666,1990-01-04,-10.4,-6.7,83,0.9,154,0.16,5.0,13.6,8.5,76
4,52.337433,-115.16666,1990-01-05,-10.1,1.6,81,0.1,183,0.29,1.0,11.8,8.7,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.337433,-115.16666,2022-12-28,-4.6,0.9,91,2.0,357,0.16,10.0,9.8,6.2,77
12050,52.337433,-115.16666,2022-12-29,-6.4,-0.7,83,0.2,222,0.27,2.0,9.2,5.8,56
12051,52.337433,-115.16666,2022-12-30,-5.2,0.4,73,0.0,223,0.32,0.0,12.2,7.8,55
12052,52.337433,-115.16666,2022-12-31,-3.5,1.2,77,0.0,265,0.36,0.0,12.0,8.2,64
12053,52.337433,-115.16666,2023-01-01,-2.1,2.7,76,1.0,257,0.34,5.0,12.0,8.1,52

### Durschnitt pro Provinz

In [14]:

# in Datetime umwandeln
for df in [Alberta_1, Alberta_2, Alberta_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Alberta_1, Alberta_2, Alberta_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Alberta_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Alberta_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-4.766667,-2.133333,79.333333,68.666667,0.600000,3.000000,9.533333,14.000000,293.333333,0.256667
1,1990-01-02,-10.100000,-6.666667,82.000000,70.333333,0.533333,4.333333,7.200000,11.266667,348.333333,0.153333
2,1990-01-03,-15.833333,-11.700000,74.666667,65.666667,1.266667,5.333333,7.933333,11.100000,199.333333,0.156667
3,1990-01-04,-18.733333,-16.500000,75.666667,67.333333,0.766667,4.333333,7.566667,11.566667,153.000000,0.110000
4,1990-01-05,-18.833333,-9.300000,79.666667,71.000000,0.433333,2.000000,9.666667,13.466667,169.333333,0.156667
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-10.066667,-7.400000,82.000000,74.666667,2.566667,11.333333,8.266667,13.500000,195.333333,0.140000
12050,2022-12-29,-12.533333,-9.000000,82.000000,67.666667,0.166667,1.666667,6.433333,9.700000,149.666667,0.150000
12051,2022-12-30,-10.333333,-5.933333,82.000000,72.666667,0.000000,0.000000,8.600000,12.333333,159.333333,0.163333
12052,2022-12-31,-8.300000,-5.133333,83.666667,74.666667,0.166667,1.666667,7.133333,10.666667,166.333333,0.176667
12053,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000

### Durschnitt pro Monat

In [15]:

Alberta_mean['time'] = pd.to_datetime(Alberta_mean['time'])

# Monats-Durchschnitt für alle Variablen
Alberta_monthly_mean = (
    Alberta_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Alberta_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-11.569892,-6.860215,76.344086,64.795699,0.592473,2.505376,10.409677,15.327957,223.365591,0.289140
1,1990-02-01,-13.560714,-6.180952,71.392857,52.857143,0.458333,1.797619,10.897619,16.297619,206.761905,0.532976
2,1990-03-01,-2.176344,5.023656,67.838710,42.827957,0.488172,1.838710,10.551613,15.489247,229.709677,1.406667
3,1990-04-01,2.753333,9.282222,64.888889,40.122222,1.252222,3.288889,10.631111,16.352222,208.500000,2.221222
4,1990-05-01,9.982796,16.177419,65.139785,39.204301,1.895699,3.483871,10.335484,16.073118,186.462366,3.430645
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.074444,21.204444,64.833333,39.666667,0.855556,2.000000,10.297778,15.964444,225.666667,2.744333
393,2022-10-01,8.090323,13.873118,65.150538,43.483871,0.744086,1.806452,11.341935,18.224731,219.032258,1.712258
394,2022-11-01,-5.663333,-1.366667,69.633333,53.433333,0.964444,4.277778,12.106667,17.871111,241.311111,0.541778
395,2022-12-01,-16.086022,-11.305376,75.344086,65.043011,0.983871,4.387097,10.149462,15.201075,215.591398,0.184946
396,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000

### Jahr und Monat in verschiedene Columns

In [16]:
# sicherstellen, dass time datetime ist
Alberta_monthly_mean['time'] = pd.to_datetime(Alberta_monthly_mean['time'])

# Jahr und Monat extrahieren
Alberta_monthly_mean['Year'] = Alberta_monthly_mean['time'].dt.year
Alberta_monthly_mean['Month'] = Alberta_monthly_mean['time'].dt.month
Alberta_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-11.569892,-6.860215,76.344086,64.795699,0.592473,2.505376,10.409677,15.327957,223.365591,0.289140,1990,1
1,1990-02-01,-13.560714,-6.180952,71.392857,52.857143,0.458333,1.797619,10.897619,16.297619,206.761905,0.532976,1990,2
2,1990-03-01,-2.176344,5.023656,67.838710,42.827957,0.488172,1.838710,10.551613,15.489247,229.709677,1.406667,1990,3
3,1990-04-01,2.753333,9.282222,64.888889,40.122222,1.252222,3.288889,10.631111,16.352222,208.500000,2.221222,1990,4
4,1990-05-01,9.982796,16.177419,65.139785,39.204301,1.895699,3.483871,10.335484,16.073118,186.462366,3.430645,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.074444,21.204444,64.833333,39.666667,0.855556,2.000000,10.297778,15.964444,225.666667,2.744333,2022,9
393,2022-10-01,8.090323,13.873118,65.150538,43.483871,0.744086,1.806452,11.341935,18.224731,219.032258,1.712258,2022,10
394,2022-11-01,-5.663333,-1.366667,69.633333,53.433333,0.964444,4.277778,12.106667,17.871111,241.311111,0.541778,2022,11
395,2022-12-01,-16.086022,-11.305376,75.344086,65.043011,0.983871,4.387097,10.149462,15.201075,215.591398,0.184946,2022,12
396,2023-01-01,-6.833333,-2.333333,81.333333,68.333333,0.333333,1.666667,9.200000,13.100000,264.666667,0.210000,2023,1

In [18]:
import os
#Datei speichern
output_path = "../data/cleaned_Alberta_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Alberta_monthly_mean.to_csv(output_path, index=False)

## Quebec

In [20]:
#Chibougamau / Eeyou Istchee Boreal Forest
#→ 49.90,-74.38

pfad = "../data/import weather data/import data/Quebec/open-meteo-49.88N74.35W429m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,49.876976,-74.34784,1990-01-01,-12.8,-8.1,81,4.7,300,0.20,15.0,25.4,17.1,69
1,49.876976,-74.34784,1990-01-02,-15.9,-6.4,81,2.3,243,0.21,13.0,23.7,16.6,75
2,49.876976,-74.34784,1990-01-03,-12.0,-6.0,78,0.9,283,0.26,5.0,20.6,13.0,68
3,49.876976,-74.34784,1990-01-04,-4.2,-1.0,86,2.6,223,0.28,16.0,19.1,16.7,78
4,49.876976,-74.34784,1990-01-05,-18.6,-9.0,75,0.0,276,0.20,0.0,20.1,14.2,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,49.876976,-74.34784,2022-12-28,-13.7,-8.6,80,1.5,167,0.19,9.0,12.6,9.3,77
12050,49.876976,-74.34784,2022-12-29,-8.1,-3.6,88,12.6,130,0.16,17.0,22.3,16.8,86
12051,49.876976,-74.34784,2022-12-30,1.7,4.4,91,1.1,197,0.23,8.0,23.6,17.2,88
12052,49.876976,-74.34784,2022-12-31,-0.3,4.2,89,0.2,259,0.21,2.0,23.0,14.2,84
12053,49.876976,-74.34784,2023-01-01,-5.8,-3.4,86,0.0,322,0.20,0.0,12.5,9.5,78

In [23]:
#La Grande / Nord-du-Québec Feuerzonen
#→ 53.60, -76.10

pfad = "../data/import weather data/import data/Quebec/open-meteo-53.60N76.03W237m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,53.60281,-76.034485,1990-01-01,-18.5,-13.7,79,1.2,298,0.11,7.0,21.9,15.3,72
1,53.60281,-76.034485,1990-01-02,-21.9,-16.0,78,1.7,195,0.11,10.0,16.2,11.3,76
2,53.60281,-76.034485,1990-01-03,-22.7,-17.3,78,0.1,254,0.09,1.0,15.1,10.3,71
3,53.60281,-76.034485,1990-01-04,-16.4,-8.5,77,2.9,219,0.21,9.0,29.6,23.4,68
4,53.60281,-76.034485,1990-01-05,-27.5,-23.1,74,0.0,255,0.09,0.0,19.8,16.3,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,53.60281,-76.034485,2022-12-28,-18.4,-17.0,79,0.7,202,0.13,7.0,17.3,9.8,74
12050,53.60281,-76.034485,2022-12-29,-15.2,-9.1,78,0.8,119,0.21,5.0,21.4,16.0,71
12051,53.60281,-76.034485,2022-12-30,-4.0,0.5,92,6.4,156,0.11,15.0,17.5,14.2,83
12052,53.60281,-76.034485,2022-12-31,-6.3,-0.8,85,2.7,249,0.21,23.0,23.1,17.8,78
12053,53.60281,-76.034485,2023-01-01,-11.3,-9.6,84,0.4,245,0.12,4.0,10.8,8.0,80

In [24]:
#Mauricie Boreal Forest Belt
#→ 47.00, -72.80

pfad = "../data/import weather data/import data/Quebec/open-meteo-46.99N72.76W381m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Quebec_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Quebec_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,46.994724,-72.759766,1990-01-01,-4.3,0.6,85,8.0,279,0.35,19.0,25.5,17.3,64
1,46.994724,-72.759766,1990-01-02,-12.7,-4.4,76,0.0,259,0.32,0.0,22.7,14.3,69
2,46.994724,-72.759766,1990-01-03,-2.9,-1.1,81,0.0,245,0.44,0.0,14.0,10.3,68
3,46.994724,-72.759766,1990-01-04,-1.6,0.4,93,7.5,179,0.19,9.0,13.7,12.5,88
4,46.994724,-72.759766,1990-01-05,-7.3,0.2,72,3.1,305,0.47,3.0,21.3,13.5,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,46.994724,-72.759766,2022-12-28,-11.8,-6.5,86,3.5,163,0.14,15.0,10.7,8.9,78
12050,46.994724,-72.759766,2022-12-29,-4.4,-1.5,92,4.3,138,0.19,13.0,16.3,10.3,83
12051,46.994724,-72.759766,2022-12-30,2.1,5.2,90,0.3,179,0.29,3.0,12.8,11.0,83
12052,46.994724,-72.759766,2022-12-31,2.7,4.4,93,9.1,177,0.23,19.0,11.8,6.6,78
12053,46.994724,-72.759766,2023-01-01,-0.3,1.2,89,6.0,345,0.34,15.0,15.4,10.7,71

### Durschnitt pro Provinz

In [25]:

# in Datetime umwandeln
for df in [Quebec_1, Quebec_2, Quebec_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Quebec_1, Quebec_2, Quebec_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Quebec_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Quebec_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-11.866667,-7.066667,81.666667,68.333333,4.633333,13.666667,16.566667,24.266667,292.333333,0.220000
1,1990-01-02,-16.833333,-8.933333,78.333333,73.333333,1.333333,7.666667,14.066667,20.866667,232.333333,0.213333
2,1990-01-03,-12.533333,-8.133333,79.000000,69.000000,0.333333,2.000000,11.200000,16.566667,260.666667,0.263333
3,1990-01-04,-7.400000,-3.033333,85.333333,78.000000,4.333333,11.333333,17.533333,20.800000,207.000000,0.226667
4,1990-01-05,-17.800000,-10.633333,73.666667,62.000000,1.033333,1.000000,14.666667,20.400000,278.666667,0.253333
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-14.633333,-10.700000,81.666667,76.333333,1.900000,10.333333,9.333333,13.533333,177.333333,0.153333
12050,2022-12-29,-9.233333,-4.733333,86.000000,80.000000,5.900000,11.666667,14.366667,20.000000,129.000000,0.186667
12051,2022-12-30,-0.066667,3.366667,91.000000,84.666667,2.600000,8.666667,14.133333,17.966667,177.333333,0.210000
12052,2022-12-31,-1.300000,2.600000,89.000000,80.000000,4.000000,14.666667,12.866667,19.300000,228.333333,0.216667
12053,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000

### Durchschnitt pro Monat

In [26]:

Quebec_mean['time'] = pd.to_datetime(Quebec_mean['time'])

# Monats-Durchschnitt für alle Variablen
Quebec_monthly_mean = (
    Quebec_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Quebec_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000

In [27]:
# Jahr und Monat extrahieren
Quebec_monthly_mean['Year'] = Quebec_monthly_mean['time'].dt.year
Quebec_monthly_mean['Month'] = Quebec_monthly_mean['time'].dt.month
Quebec_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-15.113978,-10.651613,77.838710,67.838710,1.864516,5.172043,13.095699,18.507527,200.591398,0.255376,1990,1
1,1990-02-01,-18.552381,-13.453571,71.190476,57.190476,1.430952,3.952381,13.436905,18.475000,226.773810,0.341310,1990,2
2,1990-03-01,-9.580645,-4.570968,72.978495,55.774194,1.294624,3.505376,13.438710,18.306452,235.010753,0.829462,1990,3
3,1990-04-01,-1.653333,2.888889,76.755556,58.488889,2.013333,4.555556,12.527778,18.077778,191.288889,1.523111,1990,4
4,1990-05-01,5.680645,10.969892,66.236559,44.075269,2.343011,4.204301,11.766667,17.237634,189.731183,2.760000,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.757778,16.245556,76.266667,55.833333,2.881111,4.522222,12.747778,18.021111,229.688889,2.159000,2022,9
393,2022-10-01,6.641935,10.644086,78.784946,59.989247,3.208602,6.043011,14.753763,21.101075,194.924731,1.209892,2022,10
394,2022-11-01,-1.573333,1.440000,80.000000,67.333333,3.557778,8.600000,15.678889,22.050000,219.822222,0.574556,2022,11
395,2022-12-01,-8.340860,-5.121505,80.752688,71.193548,3.148387,7.838710,15.170968,20.787097,178.548387,0.297849,2022,12
396,2023-01-01,-5.800000,-3.933333,86.333333,76.333333,2.133333,6.333333,9.400000,12.900000,304.000000,0.220000,2023,1

In [28]:
import os
#Datei speichern
output_path = "../data/cleaned_Quebec_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Quebec_monthly_mean.to_csv(output_path, index=False)

## Ontario

In [54]:
#Red Lake – eine der aktivsten Brandregionen:
#→ 51.02, -93.82

pfad = "../data/import weather data/import data/Ontario/open-meteo-51.00N93.86W356m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,51.001755,-93.864044,1990-01-01,-12.7,-8.7,80,0.0,208,0.20,0.0,27.4,14.3,71
1,51.001755,-93.864044,1990-01-02,-6.2,-4.3,83,0.0,278,0.28,0.0,21.8,14.8,74
2,51.001755,-93.864044,1990-01-03,-10.5,-7.7,85,3.7,25,0.16,9.0,20.2,11.6,76
3,51.001755,-93.864044,1990-01-04,-17.7,-13.4,77,0.1,289,0.17,1.0,18.7,12.6,67
4,51.001755,-93.864044,1990-01-05,-22.5,-21.0,76,0.0,272,0.13,0.0,10.9,8.8,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,51.001755,-93.864044,2022-12-28,-11.2,-6.5,83,0.8,95,0.22,5.0,17.3,15.5,80
12050,51.001755,-93.864044,2022-12-29,-5.9,-4.7,89,0.9,109,0.15,5.0,14.1,7.8,86
12051,51.001755,-93.864044,2022-12-30,-10.9,-5.0,82,2.3,265,0.19,10.0,15.3,12.1,71
12052,51.001755,-93.864044,2022-12-31,-15.2,-11.7,80,0.0,162,0.18,0.0,12.3,8.5,71
12053,51.001755,-93.864044,2023-01-01,-10.2,-7.8,86,0.0,74,0.14,0.0,8.4,5.0,82

In [55]:
#Sioux Lookout Boreal Forest
#→ 50.10, -91.90

pfad = "../data/import weather data/import data/Ontario/open-meteo-50.09N91.89W371m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,50.08787,-91.88812,1990-01-01,-11.8,-8.4,80,0.0,226,0.22,0.0,25.5,13.0,70
1,50.08787,-91.88812,1990-01-02,-3.5,-1.5,82,0.0,257,0.36,0.0,24.3,15.8,72
2,50.08787,-91.88812,1990-01-03,-4.7,-2.6,88,3.0,107,0.23,9.0,21.3,12.8,80
3,50.08787,-91.88812,1990-01-04,-14.1,-7.7,78,0.1,284,0.22,1.0,20.5,12.9,68
4,50.08787,-91.88812,1990-01-05,-20.6,-18.3,77,0.0,282,0.14,0.0,11.5,7.2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,50.08787,-91.88812,2022-12-28,-8.4,-4.1,85,0.4,95,0.19,3.0,16.2,12.1,80
12050,50.08787,-91.88812,2022-12-29,-4.3,-2.8,90,1.2,102,0.17,1.0,15.9,7.6,85
12051,50.08787,-91.88812,2022-12-30,-6.8,-3.2,86,1.6,268,0.20,11.0,15.9,11.6,75
12052,50.08787,-91.88812,2022-12-31,-13.8,-10.9,83,0.0,170,0.18,0.0,12.0,7.9,75
12053,50.08787,-91.88812,2023-01-01,-8.2,-6.5,86,0.3,37,0.18,3.0,8.3,5.9,80

In [57]:
#Temagami Forest Region
#→ 47.06, -80.06

pfad = "../data/import weather data/import data/Ontario/open-meteo-47.07N80.05W347m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Ontario_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Ontario_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,47.065025,-80.0488,1990-01-01,-11.5,-10.6,77,2.8,318,0.32,11.0,16.9,13.9,65
1,47.065025,-80.0488,1990-01-02,-7.3,-2.5,82,0.0,226,0.41,0.0,26.0,19.5,75
2,47.065025,-80.0488,1990-01-03,-4.6,-1.2,91,0.0,202,0.26,0.0,20.0,12.7,82
3,47.065025,-80.0488,1990-01-04,-0.4,0.6,91,5.3,243,0.23,10.0,19.5,13.1,82
4,47.065025,-80.0488,1990-01-05,-8.5,-4.0,80,0.0,287,0.27,0.0,13.4,8.8,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,47.065025,-80.0488,2022-12-28,-3.5,-0.7,89,7.9,204,0.22,16.0,17.9,13.2,85
12050,47.065025,-80.0488,2022-12-29,1.6,4.1,85,0.8,195,0.50,2.0,18.6,16.5,78
12051,47.065025,-80.0488,2022-12-30,4.3,5.6,96,1.2,209,0.23,9.0,22.1,17.8,87
12052,47.065025,-80.0488,2022-12-31,0.2,3.4,91,0.0,278,0.26,0.0,16.3,7.1,81
12053,47.065025,-80.0488,2023-01-01,-1.6,-0.7,88,0.0,312,0.34,0.0,10.5,7.5,74

### Durschnitt pro Provinz

In [58]:

# in Datetime umwandeln
for df in [Ontario_1, Ontario_2, Ontario_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Ontario_1, Ontario_2, Ontario_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Ontario_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Ontario_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-12.000000,-9.233333,79.000000,68.666667,0.933333,3.666667,13.733333,23.266667,250.666667,0.246667
1,1990-01-02,-5.666667,-2.766667,82.333333,73.666667,0.000000,0.000000,16.700000,24.033333,253.666667,0.350000
2,1990-01-03,-6.600000,-3.833333,88.000000,79.333333,2.233333,6.000000,12.366667,20.500000,111.333333,0.216667
3,1990-01-04,-10.733333,-6.833333,82.000000,72.333333,1.833333,4.000000,12.866667,19.566667,272.000000,0.206667
4,1990-01-05,-17.200000,-14.433333,77.666667,66.000000,0.000000,0.000000,8.266667,11.933333,280.333333,0.180000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-7.700000,-3.766667,85.666667,81.666667,3.033333,8.000000,13.600000,17.133333,131.333333,0.210000
12050,2022-12-29,-2.866667,-1.133333,88.000000,83.000000,0.966667,2.666667,10.633333,16.200000,135.333333,0.273333
12051,2022-12-30,-4.466667,-0.866667,88.000000,77.666667,1.700000,10.000000,13.833333,17.766667,247.333333,0.206667
12052,2022-12-31,-9.600000,-6.400000,84.666667,75.666667,0.000000,0.000000,7.833333,13.533333,203.333333,0.206667
12053,2023-01-01,-6.666667,-5.000000,86.666667,78.666667,0.100000,1.000000,6.133333,9.066667,141.000000,0.220000

### Durchschnitt Monat

In [59]:
Ontario_mean['time'] = pd.to_datetime(Ontario_mean['time'])

# Monats-Durchschnitt für alle Variablen
Ontario_monthly_mean = (
    Ontario_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Ontario_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-11.455914,-7.695699,80.537634,69.537634,1.743011,4.290323,12.251613,18.006452,208.849462,0.272688
1,1990-02-01,-13.639286,-8.882143,73.797619,58.964286,0.841667,2.511905,12.951190,18.021429,211.559524,0.465357
2,1990-03-01,-5.796774,-1.204301,73.548387,55.645161,1.098925,2.365591,12.943011,17.933333,201.989247,1.026774
3,1990-04-01,1.244444,6.698889,71.833333,50.066667,1.940000,3.155556,12.797778,18.601111,213.355556,1.925222
4,1990-05-01,8.473118,14.366667,64.602151,40.924731,2.208602,3.387097,10.852688,15.767742,168.763441,3.197634
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.878889,18.278889,75.988889,55.977778,2.564444,4.388889,12.587778,18.076667,201.588889,2.366667
393,2022-10-01,6.759140,10.692473,77.225806,59.129032,1.839785,5.225806,14.139785,19.958065,199.634409,1.278280
394,2022-11-01,-1.020000,1.848889,79.200000,66.111111,2.225556,6.377778,14.858889,20.478889,201.688889,0.604778
395,2022-12-01,-10.265591,-7.196774,80.548387,71.892473,1.762366,6.967742,13.605376,18.395699,192.784946,0.262796
396,2023-01-01,-6.666667,-5.000000,86.666667,78.666667,0.100000,1.000000,6.133333,9.066667,141.000000,0.220000

In [60]:
# Jahr und Monat extrahieren
Ontario_monthly_mean['Year'] = Ontario_monthly_mean['time'].dt.year
Ontario_monthly_mean['Month'] = Ontario_monthly_mean['time'].dt.month
Ontario_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-11.455914,-7.695699,80.537634,69.537634,1.743011,4.290323,12.251613,18.006452,208.849462,0.272688,1990,1
1,1990-02-01,-13.639286,-8.882143,73.797619,58.964286,0.841667,2.511905,12.951190,18.021429,211.559524,0.465357,1990,2
2,1990-03-01,-5.796774,-1.204301,73.548387,55.645161,1.098925,2.365591,12.943011,17.933333,201.989247,1.026774,1990,3
3,1990-04-01,1.244444,6.698889,71.833333,50.066667,1.940000,3.155556,12.797778,18.601111,213.355556,1.925222,1990,4
4,1990-05-01,8.473118,14.366667,64.602151,40.924731,2.208602,3.387097,10.852688,15.767742,168.763441,3.197634,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.878889,18.278889,75.988889,55.977778,2.564444,4.388889,12.587778,18.076667,201.588889,2.366667,2022,9
393,2022-10-01,6.759140,10.692473,77.225806,59.129032,1.839785,5.225806,14.139785,19.958065,199.634409,1.278280,2022,10
394,2022-11-01,-1.020000,1.848889,79.200000,66.111111,2.225556,6.377778,14.858889,20.478889,201.688889,0.604778,2022,11
395,2022-12-01,-10.265591,-7.196774,80.548387,71.892473,1.762366,6.967742,13.605376,18.395699,192.784946,0.262796,2022,12
396,2023-01-01,-6.666667,-5.000000,86.666667,78.666667,0.100000,1.000000,6.133333,9.066667,141.000000,0.220000,2023,1

In [61]:
import os

#Datei speichern
output_path = "../data/cleaned_Ontario_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Ontario_monthly_mean.to_csv(output_path, index=False)

## Saskatchewan

In [63]:
#Prince Albert National Park
#→ 53.96, -106.22

pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-53.95N106.19W532m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,53.954304,-106.18956,1990-01-01,-8.4,-4.6,86,0.1,242,0.18,1.0,20.1,14.9,79
1,53.954304,-106.18956,1990-01-02,-11.3,-5.2,83,0.0,4,0.11,0.0,13.4,7.9,76
2,53.954304,-106.18956,1990-01-03,-15.9,-14.1,82,2.2,324,0.09,10.0,13.4,6.6,72
3,53.954304,-106.18956,1990-01-04,-23.6,-19.3,77,0.0,287,0.08,0.0,13.3,7.6,66
4,53.954304,-106.18956,1990-01-05,-23.6,-21.3,77,0.0,250,0.08,0.0,11.7,8.2,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,53.954304,-106.18956,2022-12-28,-16.8,-15.7,78,4.4,63,0.12,24.0,12.8,10.7,73
12050,53.954304,-106.18956,2022-12-29,-18.3,-17.6,76,0.2,335,0.09,2.0,9.4,6.0,69
12051,53.954304,-106.18956,2022-12-30,-15.9,-12.6,81,0.1,176,0.12,1.0,11.6,8.4,75
12052,53.954304,-106.18956,2022-12-31,-12.9,-11.4,88,0.0,104,0.09,0.0,11.6,5.8,83
12053,53.954304,-106.18956,2023-01-01,-10.9,-8.1,87,0.0,269,0.11,0.0,10.2,6.3,81

In [64]:
#La Ronge borealer Wald
# 55.10, -105.30

pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-55.08N105.45W370m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,55.079086,-105.4491,1990-01-01,-11.2,-9.1,82,0.0,242,0.18,0.0,19.8,14.4,74
1,55.079086,-105.4491,1990-01-02,-13.8,-9.7,79,0.0,353,0.11,0.0,14.9,8.1,74
2,55.079086,-105.4491,1990-01-03,-17.8,-16.0,80,0.8,313,0.08,6.0,15.1,6.7,72
3,55.079086,-105.4491,1990-01-04,-25.0,-20.9,75,0.0,280,0.09,0.0,15.6,10.3,70
4,55.079086,-105.4491,1990-01-05,-26.6,-22.2,74,0.0,255,0.08,0.0,12.5,9.5,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,55.079086,-105.4491,2022-12-28,-17.5,-15.9,77,3.4,79,0.17,23.0,20.8,17.8,74
12050,55.079086,-105.4491,2022-12-29,-19.2,-18.7,74,0.5,2,0.08,5.0,10.7,6.2,72
12051,55.079086,-105.4491,2022-12-30,-19.4,-15.7,79,0.0,116,0.09,0.0,11.0,6.1,72
12052,55.079086,-105.4491,2022-12-31,-13.7,-11.4,83,0.0,131,0.08,0.0,8.9,4.4,73
12053,55.079086,-105.4491,2023-01-01,-11.7,-8.9,85,0.0,249,0.10,0.0,7.3,5.3,77

In [65]:
#Meadow Lake Provincial Park
#→ 54.14, -108.44
pfad = "../data/import weather data/import data/Saskatchewan/open-meteo-54.17N108.39W483m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Saskatchewan_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Saskatchewan_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,54.1652,-108.38522,1990-01-01,-5.8,-2.5,87,0.2,254,0.17,2.0,14.8,10.7,75
1,54.1652,-108.38522,1990-01-02,-11.6,-4.7,86,0.0,18,0.10,0.0,11.7,7.3,76
2,54.1652,-108.38522,1990-01-03,-17.1,-13.7,82,1.4,338,0.10,6.0,9.9,5.9,71
3,54.1652,-108.38522,1990-01-04,-24.5,-18.9,76,0.0,299,0.08,0.0,9.3,4.2,68
4,54.1652,-108.38522,1990-01-05,-23.0,-16.3,80,0.0,211,0.08,0.0,9.5,6.5,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,54.1652,-108.38522,2022-12-28,-14.6,-14.2,77,3.1,59,0.17,16.0,16.6,11.9,73
12050,54.1652,-108.38522,2022-12-29,-15.9,-14.9,74,0.2,46,0.09,2.0,7.3,3.6,72
12051,54.1652,-108.38522,2022-12-30,-15.6,-11.3,85,0.0,120,0.09,0.0,7.7,3.9,77
12052,54.1652,-108.38522,2022-12-31,-12.1,-10.6,87,0.0,25,0.09,0.0,6.3,3.7,82
12053,54.1652,-108.38522,2023-01-01,-10.4,-7.5,86,0.0,243,0.11,0.0,13.9,8.9,85

### Durchschnitt pro Provinz

In [66]:

for df in [Saskatchewan_1, Saskatchewan_2, Saskatchewan_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Saskatchewan_1, Saskatchewan_2, Saskatchewan_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Saskatchewan_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Saskatchewan_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-8.466667,-5.400000,85.000000,76.000000,0.100000,1.000000,13.333333,18.233333,246.000000,0.176667
1,1990-01-02,-12.233333,-6.533333,82.666667,75.333333,0.000000,0.000000,7.766667,13.333333,125.000000,0.106667
2,1990-01-03,-16.933333,-14.600000,81.333333,71.666667,1.466667,7.333333,6.400000,12.800000,325.000000,0.090000
3,1990-01-04,-24.366667,-19.700000,76.000000,68.000000,0.000000,0.000000,7.366667,12.733333,288.666667,0.083333
4,1990-01-05,-24.400000,-19.933333,77.000000,72.000000,0.000000,0.000000,8.066667,11.233333,238.666667,0.080000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-16.300000,-15.266667,77.333333,73.333333,3.633333,21.000000,13.466667,16.733333,67.000000,0.153333
12050,2022-12-29,-17.800000,-17.066667,74.666667,71.000000,0.300000,3.000000,5.266667,9.133333,127.666667,0.086667
12051,2022-12-30,-16.966667,-13.200000,81.666667,74.666667,0.033333,0.333333,6.133333,10.100000,137.333333,0.100000
12052,2022-12-31,-12.900000,-11.133333,86.000000,79.333333,0.000000,0.000000,4.633333,8.933333,86.666667,0.086667
12053,2023-01-01,-11.000000,-8.166667,86.000000,81.000000,0.000000,0.000000,6.833333,10.466667,253.666667,0.106667

### Durchschnitt pro Monat

In [67]:
Saskatchewan_mean['time'] = pd.to_datetime(Saskatchewan_mean['time'])

# Monats-Durchschnitt für alle Variablen
Saskatchewan_monthly_mean = (
    Saskatchewan_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Saskatchewan_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-14.477419,-10.540860,80.612903,71.344086,0.587097,2.247312,10.807527,15.573118,226.860215,0.174301
1,1990-02-01,-17.078571,-11.145238,74.785714,61.059524,0.551190,1.916667,10.839286,15.148810,212.750000,0.356071
2,1990-03-01,-4.513978,0.586022,76.827957,60.666667,0.411828,1.473118,12.686022,17.097849,205.569892,1.018065
3,1990-04-01,0.884444,6.568889,69.633333,47.388889,2.073333,3.788889,11.662222,16.811111,199.288889,1.848111
4,1990-05-01,8.650538,15.210753,66.903226,40.580645,1.137634,2.354839,10.504301,15.512903,160.483871,3.359677
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.188889,20.246667,68.466667,44.211111,1.002222,2.022222,11.503333,18.657778,213.755556,2.666222
393,2022-10-01,6.903226,11.948387,65.752688,46.279570,0.373118,1.817204,12.601075,17.882796,208.225806,1.591183
394,2022-11-01,-6.371111,-3.567778,85.377778,75.822222,1.778889,6.577778,13.566667,18.736667,194.233333,0.278000
395,2022-12-01,-18.429032,-15.166667,78.860215,71.903226,0.920430,4.333333,10.873118,15.650538,182.301075,0.124516
396,2023-01-01,-11.000000,-8.166667,86.000000,81.000000,0.000000,0.000000,6.833333,10.466667,253.666667,0.106667

In [68]:
# Jahr und Monat extrahieren
Saskatchewan_monthly_mean['Year'] = Saskatchewan_monthly_mean['time'].dt.year
Saskatchewan_monthly_mean['Month'] = Saskatchewan_monthly_mean['time'].dt.month
Saskatchewan_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-14.477419,-10.540860,80.612903,71.344086,0.587097,2.247312,10.807527,15.573118,226.860215,0.174301,1990,1
1,1990-02-01,-17.078571,-11.145238,74.785714,61.059524,0.551190,1.916667,10.839286,15.148810,212.750000,0.356071,1990,2
2,1990-03-01,-4.513978,0.586022,76.827957,60.666667,0.411828,1.473118,12.686022,17.097849,205.569892,1.018065,1990,3
3,1990-04-01,0.884444,6.568889,69.633333,47.388889,2.073333,3.788889,11.662222,16.811111,199.288889,1.848111,1990,4
4,1990-05-01,8.650538,15.210753,66.903226,40.580645,1.137634,2.354839,10.504301,15.512903,160.483871,3.359677,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,14.188889,20.246667,68.466667,44.211111,1.002222,2.022222,11.503333,18.657778,213.755556,2.666222,2022,9
393,2022-10-01,6.903226,11.948387,65.752688,46.279570,0.373118,1.817204,12.601075,17.882796,208.225806,1.591183,2022,10
394,2022-11-01,-6.371111,-3.567778,85.377778,75.822222,1.778889,6.577778,13.566667,18.736667,194.233333,0.278000,2022,11
395,2022-12-01,-18.429032,-15.166667,78.860215,71.903226,0.920430,4.333333,10.873118,15.650538,182.301075,0.124516,2022,12
396,2023-01-01,-11.000000,-8.166667,86.000000,81.000000,0.000000,0.000000,6.833333,10.466667,253.666667,0.106667,2023,1

In [69]:
import os

#Datei speichern
output_path = "../data/cleaned_Saskatchewan_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Saskatchewan_monthly_mean.to_csv(output_path, index=False)

## Manitoba

In [70]:
#Thompson boreale Waldregion
#→ 55.74, -97.86

pfad = "../data/import weather data/import data/Manitoba/open-meteo-55.71N97.87W206m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Manitoba_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Manitoba_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,55.711773,-97.865845,1990-01-01,-17.0,-13.6,78,0.0,178,0.12,0.0,15.5,10.2,76
1,55.711773,-97.865845,1990-01-02,-18.9,-13.8,78,0.0,320,0.11,0.0,15.3,10.8,71
2,55.711773,-97.865845,1990-01-03,-22.6,-21.6,77,2.5,315,0.05,13.0,9.2,4.8,71
3,55.711773,-97.865845,1990-01-04,-26.0,-22.0,73,0.0,287,0.08,0.0,12.7,11.8,64
4,55.711773,-97.865845,1990-01-05,-28.8,-25.1,72,0.0,268,0.08,0.0,13.7,11.9,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,55.711773,-97.865845,2022-12-28,-25.5,-20.6,74,0.0,63,0.09,0.0,17.4,13.2,68
12050,55.711773,-97.865845,2022-12-29,-17.8,-15.5,77,6.9,58,0.12,24.0,15.3,10.6,75
12051,55.711773,-97.865845,2022-12-30,-14.8,-13.8,82,2.7,7,0.06,20.0,6.9,3.7,74
12052,55.711773,-97.865845,2022-12-31,-17.8,-15.3,82,0.0,165,0.07,0.0,10.8,8.0,72
12053,55.711773,-97.865845,2023-01-01,-16.0,-14.3,82,0.0,284,0.07,0.0,8.6,5.1,73

In [71]:
#Flin Flon – waldreich, feueranfällig
#→ 54.77, -101.87

pfad = "../data/import weather data/import data/Manitoba/open-meteo-54.80N101.94W338m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Manitoba_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Manitoba_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,54.79789,-101.94058,1990-01-01,-14.3,-10.6,79,0.0,191,0.17,0.0,18.0,12.9,75
1,54.79789,-101.94058,1990-01-02,-16.5,-10.8,78,0.0,340,0.13,0.0,17.1,9.9,71
2,54.79789,-101.94058,1990-01-03,-19.6,-19.3,78,1.9,338,0.08,9.0,12.5,5.3,73
3,54.79789,-101.94058,1990-01-04,-24.9,-21.4,75,0.0,288,0.09,0.0,13.3,11.3,68
4,54.79789,-101.94058,1990-01-05,-27.5,-25.1,72,0.0,269,0.09,0.0,14.5,10.6,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,54.79789,-101.94058,2022-12-28,-20.9,-19.3,76,4.1,64,0.11,13.0,15.1,13.2,74
12050,54.79789,-101.94058,2022-12-29,-19.8,-18.0,74,2.9,358,0.10,18.0,9.6,7.2,69
12051,54.79789,-101.94058,2022-12-30,-19.1,-17.5,77,0.5,248,0.07,5.0,8.6,5.1,71
12052,54.79789,-101.94058,2022-12-31,-16.3,-13.3,82,0.0,133,0.10,0.0,12.7,8.4,78
12053,54.79789,-101.94058,2023-01-01,-14.0,-12.4,84,0.3,324,0.09,3.0,7.1,4.6,75

In [72]:
#Atikaki Provincial Wilderness
#→ 51.23, -95.28

pfad = "../data/import weather data/import data/Manitoba/open-meteo-51.21N95.34W324m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Manitoba_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Manitoba_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,51.21265,-95.341705,1990-01-01,-13.0,-5.6,80,0.0,201,0.23,0.0,24.2,14.7,68
1,51.21265,-95.341705,1990-01-02,-7.2,-3.5,84,0.0,295,0.22,0.0,19.9,12.3,71
2,51.21265,-95.341705,1990-01-03,-12.4,-10.6,83,3.7,360,0.16,9.0,17.5,11.0,71
3,51.21265,-95.341705,1990-01-04,-18.9,-15.5,79,0.4,286,0.13,3.0,12.2,9.9,65
4,51.21265,-95.341705,1990-01-05,-23.6,-20.9,76,0.0,261,0.11,0.0,9.6,7.4,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,51.21265,-95.341705,2022-12-28,-11.0,-6.2,81,1.9,97,0.24,8.0,17.5,14.4,77
12050,51.21265,-95.341705,2022-12-29,-6.0,-5.0,89,3.5,123,0.15,9.0,13.3,7.3,84
12051,51.21265,-95.341705,2022-12-30,-14.2,-9.8,80,1.3,259,0.15,7.0,11.8,10.1,72
12052,51.21265,-95.341705,2022-12-31,-14.2,-7.0,84,0.0,143,0.17,0.0,11.0,8.5,78
12053,51.21265,-95.341705,2023-01-01,-8.9,-6.8,87,0.0,120,0.14,0.0,8.2,4.6,82

### Durchschnitt pro Provinz

In [73]:
for df in [Manitoba_1, Manitoba_2, Manitoba_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Manitoba_1, Manitoba_2, Manitoba_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Manitoba_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Manitoba_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-14.766667,-9.933333,79.000000,73.000000,0.000000,0.000000,12.600000,19.233333,190.000000,0.173333
1,1990-01-02,-14.200000,-9.366667,80.000000,71.000000,0.000000,0.000000,11.000000,17.433333,318.333333,0.153333
2,1990-01-03,-18.200000,-17.166667,79.333333,71.666667,2.700000,10.333333,7.033333,13.066667,337.666667,0.096667
3,1990-01-04,-23.266667,-19.633333,75.666667,65.666667,0.133333,1.000000,11.000000,12.733333,287.000000,0.100000
4,1990-01-05,-26.633333,-23.700000,73.333333,65.333333,0.000000,0.000000,9.966667,12.600000,266.000000,0.093333
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-19.133333,-15.366667,77.000000,73.000000,2.000000,7.000000,13.600000,16.666667,74.666667,0.146667
12050,2022-12-29,-14.533333,-12.833333,80.000000,76.000000,4.433333,17.000000,8.366667,12.733333,179.666667,0.123333
12051,2022-12-30,-16.033333,-13.700000,79.666667,72.333333,1.500000,10.666667,6.300000,9.100000,171.333333,0.093333
12052,2022-12-31,-16.100000,-11.866667,82.666667,76.000000,0.000000,0.000000,8.300000,11.500000,147.000000,0.113333
12053,2023-01-01,-12.966667,-11.166667,84.333333,76.666667,0.100000,1.000000,4.766667,7.966667,242.666667,0.100000

### Durchschnitt in Monat

In [74]:
Manitoba_mean['time'] = pd.to_datetime(Manitoba_mean['time'])

# Monats-Durchschnitt für alle Variablen
Manitoba_monthly_mean = (
    Manitoba_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Manitoba_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-18.223656,-14.378495,77.451613,68.376344,0.907527,2.559140,10.686022,15.416129,218.311828,0.155591
1,1990-02-01,-19.783333,-14.930952,71.809524,57.797619,0.423810,1.642857,11.214286,16.030952,216.785714,0.304167
2,1990-03-01,-6.825806,-1.859140,72.612903,55.666667,0.759140,1.860215,13.917204,18.629032,206.903226,0.898925
3,1990-04-01,-1.973333,3.901111,69.088889,49.211111,1.784444,3.166667,12.524444,17.714444,205.144444,1.615333
4,1990-05-01,7.700000,14.404301,61.473118,36.720430,0.822581,1.978495,10.708602,15.726882,164.086022,3.379892
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.111111,18.485556,73.200000,49.755556,1.392222,2.766667,12.102222,17.478889,212.455556,2.404111
393,2022-10-01,4.529032,8.666667,76.290323,57.666667,1.848387,4.322581,13.473118,19.130108,221.548387,1.118065
394,2022-11-01,-7.207778,-3.997778,82.388889,70.700000,1.785556,6.844444,12.364444,17.466667,195.233333,0.308889
395,2022-12-01,-18.241935,-15.137634,78.892473,71.462366,0.986022,5.053763,10.958065,14.741935,197.107527,0.126667
396,2023-01-01,-12.966667,-11.166667,84.333333,76.666667,0.100000,1.000000,4.766667,7.966667,242.666667,0.100000

In [75]:
# Jahr und Monat extrahieren
Manitoba_monthly_mean['Year'] = Manitoba_monthly_mean['time'].dt.year
Manitoba_monthly_mean['Month'] = Manitoba_monthly_mean['time'].dt.month
Manitoba_monthly_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-18.223656,-14.378495,77.451613,68.376344,0.907527,2.559140,10.686022,15.416129,218.311828,0.155591,1990,1
1,1990-02-01,-19.783333,-14.930952,71.809524,57.797619,0.423810,1.642857,11.214286,16.030952,216.785714,0.304167,1990,2
2,1990-03-01,-6.825806,-1.859140,72.612903,55.666667,0.759140,1.860215,13.917204,18.629032,206.903226,0.898925,1990,3
3,1990-04-01,-1.973333,3.901111,69.088889,49.211111,1.784444,3.166667,12.524444,17.714444,205.144444,1.615333,1990,4
4,1990-05-01,7.700000,14.404301,61.473118,36.720430,0.822581,1.978495,10.708602,15.726882,164.086022,3.379892,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.111111,18.485556,73.200000,49.755556,1.392222,2.766667,12.102222,17.478889,212.455556,2.404111,2022,9
393,2022-10-01,4.529032,8.666667,76.290323,57.666667,1.848387,4.322581,13.473118,19.130108,221.548387,1.118065,2022,10
394,2022-11-01,-7.207778,-3.997778,82.388889,70.700000,1.785556,6.844444,12.364444,17.466667,195.233333,0.308889,2022,11
395,2022-12-01,-18.241935,-15.137634,78.892473,71.462366,0.986022,5.053763,10.958065,14.741935,197.107527,0.126667,2022,12
396,2023-01-01,-12.966667,-11.166667,84.333333,76.666667,0.100000,1.000000,4.766667,7.966667,242.666667,0.100000,2023,1

In [76]:
import os

#Datei speichern
output_path = "../data/cleaned_Manitoba_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Manitoba_monthly_mean.to_csv(output_path, index=False)

## New Brunswick

In [77]:
#Miramichi Hinterland Forest
#→ 46.98, -65.52

pfad = "../data/import weather data/import data/New Brunswick/open-meteo-46.99N65.45W39m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
New_Brunswick_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

New_Brunswick_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,46.994724,-65.45456,1990-01-01,-0.5,2.9,92,13.0,214,0.24,16.0,25.0,13.8,69
1,46.994724,-65.45456,1990-01-02,-9.3,-3.0,62,0.0,271,0.69,0.0,26.3,21.1,53
2,46.994724,-65.45456,1990-01-03,-5.5,-1.9,76,0.0,259,0.54,0.0,20.3,14.5,54
3,46.994724,-65.45456,1990-01-04,-4.7,1.9,84,0.1,187,0.35,1.0,16.2,11.4,79
4,46.994724,-65.45456,1990-01-05,-1.7,3.2,74,2.6,261,0.65,5.0,23.9,17.8,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,46.994724,-65.45456,2022-12-28,-11.2,-6.3,77,0.4,247,0.28,4.0,14.1,8.5,65
12050,46.994724,-65.45456,2022-12-29,-8.7,-5.0,84,1.6,285,0.19,6.0,9.7,5.4,71
12051,46.994724,-65.45456,2022-12-30,-0.3,5.1,86,1.4,186,0.38,5.0,12.6,7.1,76
12052,46.994724,-65.45456,2022-12-31,4.8,7.5,90,0.1,223,0.38,1.0,18.6,14.3,84
12053,46.994724,-65.45456,2023-01-01,1.4,2.6,98,23.8,15,0.11,23.0,19.7,10.3,88

In [78]:
#Mount Carleton Provincial Park
#→ 47.39, -66.86

pfad = "../data/import weather data/import data/New Brunswick/open-meteo-47.42N66.69W593m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
New_Brunswick_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

New_Brunswick_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,47.41652,-66.68851,1990-01-01,-1.4,1.4,93,13.3,223,0.22,18.0,29.5,18.2,75
1,47.41652,-66.68851,1990-01-02,-13.9,-8.7,70,0.0,284,0.45,0.0,33.5,28.0,63
2,47.41652,-66.68851,1990-01-03,-8.3,-6.1,79,0.0,283,0.45,0.0,26.0,21.5,59
3,47.41652,-66.68851,1990-01-04,-5.6,0.1,84,0.5,205,0.33,2.0,16.8,12.6,78
4,47.41652,-66.68851,1990-01-05,-6.3,0.8,77,3.8,276,0.42,7.0,25.0,20.9,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,47.41652,-66.68851,2022-12-28,-15.7,-10.0,81,1.2,246,0.20,8.0,14.6,10.2,70
12050,47.41652,-66.68851,2022-12-29,-9.5,-7.1,88,4.3,219,0.17,11.0,10.9,5.3,75
12051,47.41652,-66.68851,2022-12-30,-1.4,3.2,91,0.9,212,0.24,5.0,15.9,13.6,87
12052,47.41652,-66.68851,2022-12-31,3.7,4.7,92,4.9,238,0.28,21.0,19.4,14.7,87
12053,47.41652,-66.68851,2023-01-01,0.2,2.2,98,21.6,16,0.13,23.0,15.3,8.3,89

In [79]:
#Northumberland County Boreal Edge
#→ 46.96, -65.06

pfad = "../data/import weather data/import data/New Brunswick/open-meteo-46.99N65.02W25m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
New_Brunswick_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

New_Brunswick_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,46.994724,-65.016235,1990-01-01,0.4,3.3,92,15.4,209,0.26,18.0,26.6,19.5,73
1,46.994724,-65.016235,1990-01-02,-8.8,-1.9,64,0.0,269,0.74,0.0,32.0,27.3,56
2,46.994724,-65.016235,1990-01-03,-5.5,-2.3,77,0.0,257,0.57,0.0,23.0,20.0,60
3,46.994724,-65.016235,1990-01-04,-4.3,2.1,83,0.1,189,0.41,1.0,21.3,14.8,76
4,46.994724,-65.016235,1990-01-05,-1.5,3.1,75,2.4,260,0.69,5.0,29.9,23.1,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,46.994724,-65.016235,2022-12-28,-10.9,-6.3,74,0.6,253,0.33,6.0,17.8,9.4,63
12050,46.994724,-65.016235,2022-12-29,-8.6,-5.0,86,1.0,269,0.24,6.0,11.2,6.4,70
12051,46.994724,-65.016235,2022-12-30,0.1,6.0,86,1.6,187,0.39,7.0,16.9,9.9,72
12052,46.994724,-65.016235,2022-12-31,5.4,7.8,88,0.1,228,0.47,1.0,21.1,15.3,82
12053,46.994724,-65.016235,2023-01-01,1.8,3.4,98,25.1,9,0.11,24.0,24.2,12.4,93

### Durchschnitt pro Provinz

In [85]:
for df in [New_Brunswick_1, New_Brunswick_2, New_Brunswick_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [New_Brunswick_1, New_Brunswick_2, New_Brunswick_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
New_Brunswick_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

New_Brunswick_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-0.500000,2.533333,92.333333,72.333333,13.900000,17.333333,17.166667,27.033333,215.333333,0.240000
1,1990-01-02,-10.666667,-4.533333,65.333333,57.333333,0.000000,0.000000,25.466667,30.600000,274.666667,0.626667
2,1990-01-03,-6.433333,-3.433333,77.333333,57.666667,0.000000,0.000000,18.666667,23.100000,266.333333,0.520000
3,1990-01-04,-4.866667,1.366667,83.666667,77.666667,0.233333,1.333333,12.933333,18.100000,193.666667,0.363333
4,1990-01-05,-3.166667,2.366667,75.333333,56.000000,2.933333,5.666667,20.600000,26.266667,265.666667,0.586667
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-12.600000,-7.533333,77.333333,66.000000,0.733333,6.000000,9.366667,15.500000,248.666667,0.270000
12050,2022-12-29,-8.933333,-5.700000,86.000000,72.000000,2.300000,7.666667,5.700000,10.600000,257.666667,0.200000
12051,2022-12-30,-0.533333,4.766667,87.666667,78.333333,1.300000,5.666667,10.200000,15.133333,195.000000,0.336667
12052,2022-12-31,4.633333,6.666667,90.000000,84.333333,1.700000,7.666667,14.766667,19.700000,229.666667,0.376667
12053,2023-01-01,1.133333,2.733333,98.000000,90.000000,23.500000,23.333333,10.333333,19.733333,13.333333,0.116667

### Durchschnitt pro Provinz

In [86]:
New_Brunswick_mean['time'] = pd.to_datetime(New_Brunswick_mean['time'])

# Monats-Durchschnitt für alle Variablen
New_Brunswick_mean = (
    New_Brunswick_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

New_Brunswick_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-8.201075,-3.587097,79.870968,67.397849,3.804301,5.774194,15.022581,21.770968,227.182796,0.409462
1,1990-02-01,-11.107143,-6.042857,72.107143,55.154762,2.192857,4.214286,14.645238,21.201190,234.904762,0.575952
2,1990-03-01,-4.907527,-0.129032,71.752688,54.096774,1.292473,2.440860,14.306452,19.825806,226.096774,1.170108
3,1990-04-01,1.967778,6.658889,76.288889,58.355556,3.412222,5.855556,13.614444,19.045556,166.700000,1.764222
4,1990-05-01,6.974194,11.433333,76.064516,56.075269,5.126882,7.505376,14.832258,20.594624,141.118280,2.313763
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.857778,18.475556,76.533333,55.222222,3.468889,3.666667,12.066667,17.335556,207.333333,2.561444
393,2022-10-01,10.026882,15.192473,75.021505,55.000000,2.682796,2.709677,12.295699,17.849462,215.387097,1.690215
394,2022-11-01,1.386667,5.028889,72.866667,57.322222,4.505556,4.444444,14.981111,22.082222,236.144444,0.990778
395,2022-12-01,-3.341935,0.140860,79.333333,65.397849,4.861290,7.408602,15.501075,22.804301,193.677419,0.454731
396,2023-01-01,1.133333,2.733333,98.000000,90.000000,23.500000,23.333333,10.333333,19.733333,13.333333,0.116667

In [88]:
# Jahr und Monat extrahieren
New_Brunswick_mean['Year'] = New_Brunswick_mean['time'].dt.year
New_Brunswick_mean['Month'] = New_Brunswick_mean['time'].dt.month
New_Brunswick_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-8.201075,-3.587097,79.870968,67.397849,3.804301,5.774194,15.022581,21.770968,227.182796,0.409462,1990,1
1,1990-02-01,-11.107143,-6.042857,72.107143,55.154762,2.192857,4.214286,14.645238,21.201190,234.904762,0.575952,1990,2
2,1990-03-01,-4.907527,-0.129032,71.752688,54.096774,1.292473,2.440860,14.306452,19.825806,226.096774,1.170108,1990,3
3,1990-04-01,1.967778,6.658889,76.288889,58.355556,3.412222,5.855556,13.614444,19.045556,166.700000,1.764222,1990,4
4,1990-05-01,6.974194,11.433333,76.064516,56.075269,5.126882,7.505376,14.832258,20.594624,141.118280,2.313763,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,13.857778,18.475556,76.533333,55.222222,3.468889,3.666667,12.066667,17.335556,207.333333,2.561444,2022,9
393,2022-10-01,10.026882,15.192473,75.021505,55.000000,2.682796,2.709677,12.295699,17.849462,215.387097,1.690215,2022,10
394,2022-11-01,1.386667,5.028889,72.866667,57.322222,4.505556,4.444444,14.981111,22.082222,236.144444,0.990778,2022,11
395,2022-12-01,-3.341935,0.140860,79.333333,65.397849,4.861290,7.408602,15.501075,22.804301,193.677419,0.454731,2022,12
396,2023-01-01,1.133333,2.733333,98.000000,90.000000,23.500000,23.333333,10.333333,19.733333,13.333333,0.116667,2023,1

In [89]:
import os

#Datei speichern
output_path = "../data/cleaned_New_Brunswick_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

New_Brunswick_mean.to_csv(output_path, index=False)

## Nova Scotia

In [ ]:

#Yarmouth County Forest (größte Feuerregion NS)
#→ 43.90, -65.95

pfad = "../data/import weather data/import data/Nova Scotia/open-meteo-46.99N65.02W25m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
New_Brunswick_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

New_Brunswick_3

In [ ]:
#Guysborough County Forests
#→ 45.19, -61.60

In [ ]:
#Keji Nationalpark
#→ 44.43, -65.23

In [ ]:
for df in [New_Brunswick_1, New_Brunswick_2, New_Brunswick_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [New_Brunswick_1, New_Brunswick_2, New_Brunswick_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
New_Brunswick_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

New_Brunswick_mean

In [ ]:
New_Brunswick_mean['time'] = pd.to_datetime(New_Brunswick_mean['time'])

# Monats-Durchschnitt für alle Variablen
New_Brunswick_mean = (
    New_Brunswick_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

New_Brunswick_mean

In [ ]:
# Jahr und Monat extrahieren
New_Brunswick_mean['Year'] = New_Brunswick_mean['time'].dt.year
New_Brunswick_mean['Month'] = New_Brunswick_mean['time'].dt.month
New_Brunswick_mean

In [ ]:
import os

#Datei speichern
output_path = "../data/cleaned_New_Brunswick_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

New_Brunswick_mean.to_csv(output_path, index=False)

##  Newfoundland and Labrador

In [91]:
#Labrador – Churchill Falls borealer Wald
#→ 53.55, -64.03

pfad = "../data/import weather data/import data/ Newfoundland and Labrador/open-meteo-53.53N64.02W444m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Newfoundland_and_Labrador_1 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Newfoundland_and_Labrador_1

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,53.532513,-64.01532,1990-01-01,-15.4,-10.3,85,8.8,157,0.12,19.0,22.5,11.9,77
1,53.532513,-64.01532,1990-01-02,-19.6,-13.4,74,1.4,292,0.22,6.0,40.4,35.2,72
2,53.532513,-64.01532,1990-01-03,-23.5,-22.8,73,0.0,288,0.16,0.0,28.7,24.6,70
3,53.532513,-64.01532,1990-01-04,-21.6,-15.1,77,0.9,223,0.13,5.0,22.2,16.4,72
4,53.532513,-64.01532,1990-01-05,-20.4,-14.3,73,1.1,278,0.18,5.0,28.6,23.9,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,53.532513,-64.01532,2022-12-28,-19.6,-18.6,72,0.0,265,0.21,0.0,21.2,19.9,68
12050,53.532513,-64.01532,2022-12-29,-17.9,-15.1,78,0.0,273,0.16,0.0,18.8,14.8,76
12051,53.532513,-64.01532,2022-12-30,-15.2,-8.3,80,2.1,134,0.13,11.0,10.8,7.3,73
12052,53.532513,-64.01532,2022-12-31,-2.3,1.1,87,9.1,256,0.25,8.0,24.6,18.6,81
12053,53.532513,-64.01532,2023-01-01,-9.1,-4.4,80,0.1,302,0.20,1.0,18.9,12.2,74

In [92]:
#Labrador City Forest Zone
#→ 52.95, -66.92


pfad = "../data/import weather data/import data/ Newfoundland and Labrador/open-meteo-52.97N66.95W553m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Newfoundland_and_Labrador_2 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Newfoundland_and_Labrador_2

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,52.97012,-66.94916,1990-01-01,-12.2,-10.5,82,8.0,237,0.20,20.0,37.8,18.8,71
1,52.97012,-66.94916,1990-01-02,-25.0,-18.4,73,0.0,292,0.17,0.0,43.5,35.9,71
2,52.97012,-66.94916,1990-01-03,-24.2,-22.0,76,0.0,289,0.14,0.0,31.2,23.2,71
3,52.97012,-66.94916,1990-01-04,-18.5,-8.9,79,1.3,210,0.19,7.0,27.3,19.9,72
4,52.97012,-66.94916,1990-01-05,-22.1,-8.9,73,0.6,285,0.18,2.0,28.5,26.5,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,52.97012,-66.94916,2022-12-28,-21.2,-20.3,74,0.0,266,0.18,0.0,22.0,20.0,72
12050,52.97012,-66.94916,2022-12-29,-19.7,-17.1,79,0.0,282,0.16,0.0,21.2,15.0,76
12051,52.97012,-66.94916,2022-12-30,-11.4,-5.2,84,4.8,174,0.16,15.0,22.5,13.3,80
12052,52.97012,-66.94916,2022-12-31,-1.3,1.2,90,4.2,259,0.24,16.0,29.0,22.2,83
12053,52.97012,-66.94916,2023-01-01,-9.2,-3.8,82,0.0,324,0.18,0.0,18.2,9.4,80

In [93]:
#Newfoundland – Terra Nova National Park
#→ 48.55, -53.97


pfad = "../data/import weather data/import data/ Newfoundland and Labrador/open-meteo-48.54N53.94W48m.csv"

# -------------------------------------------------------
# 1) Koordinaten aus Zeile 2 (Index 1) einlesen
# -------------------------------------------------------
coords = pd.read_csv(pfad, nrows=2, header=None)
lat = coords.iloc[1, 0]
lon = coords.iloc[1, 1]

df = pd.read_csv(
    pfad,
    skiprows=3,   # Metadaten überspringen
    comment="#",  # ignoriert eventuelle Kommentarzeilen
)

df["latitude"] = lat
df["longitude"] = lon

# Falls du die Spalten vorne haben willst:
Newfoundland_and_Labrador_3 = df[["latitude", "longitude"] + [col for col in df.columns if col not in ["latitude", "longitude"]]]

Newfoundland_and_Labrador_3

,latitude,longitude,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),precipitation_sum (mm),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),precipitation_hours (h),wind_speed_10m_max (km/h),wind_speed_10m_mean (km/h),relative_humidity_2m_min (%)
0,48.541298,-53.939392,1990-01-01,-3.9,6.9,88,4.8,191,0.20,12.0,34.8,18.3,81
1,48.541298,-53.939392,1990-01-02,-1.4,7.1,74,4.1,244,0.68,8.0,34.9,29.5,57
2,48.541298,-53.939392,1990-01-03,-6.9,-4.5,68,0.0,263,0.74,0.0,33.0,25.4,60
3,48.541298,-53.939392,1990-01-04,-10.0,-6.9,73,0.0,268,0.45,0.0,22.2,15.2,58
4,48.541298,-53.939392,1990-01-05,0.5,4.4,81,0.6,224,0.69,4.0,26.8,22.2,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12049,48.541298,-53.939392,2022-12-28,-2.8,1.9,70,2.7,263,0.61,6.0,25.1,15.1,49
12050,48.541298,-53.939392,2022-12-29,-6.3,-5.5,62,0.0,283,0.71,0.0,26.4,18.7,50
12051,48.541298,-53.939392,2022-12-30,-5.3,-1.7,69,0.0,276,0.54,0.0,15.9,10.4,45
12052,48.541298,-53.939392,2022-12-31,0.9,4.7,91,2.5,221,0.23,10.0,25.6,18.9,77
12053,48.541298,-53.939392,2023-01-01,2.7,4.2,98,14.9,255,0.15,14.0,19.7,11.6,96

### Durchschnitt pro Provinz

In [96]:
for df in [Newfoundland_and_Labrador_1, Newfoundland_and_Labrador_2, Newfoundland_and_Labrador_3]:
    df['time'] = pd.to_datetime(df['time'])

#  drei DataFrames zusammenführen
bc_all = pd.concat(
    [Newfoundland_and_Labrador_1, Newfoundland_and_Labrador_2, Newfoundland_and_Labrador_3],
    ignore_index=True
)

# Wetterspalten definieren
weather_columns = [
    'temperature_2m_mean (°C)',
    'temperature_2m_max (°C)',
    'relative_humidity_2m_mean (%)',
    'relative_humidity_2m_min (%)',
    'precipitation_sum (mm)',
    'precipitation_hours (h)',
    'wind_speed_10m_mean (km/h)',
    'wind_speed_10m_max (km/h)',
    'wind_direction_10m_dominant (°)',
    'et0_fao_evapotranspiration (mm)'
]

# Tagesdurchschnitt über alle 3 Koordinatenpunkte berechnen
Newfoundland_and_Labrador_mean = (
    bc_all
    .groupby('time')[weather_columns]
    .mean()
    .reset_index()
)

Newfoundland_and_Labrador_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-10.500000,-4.633333,85.000000,76.333333,7.200000,17.000000,16.333333,31.700000,195.000000,0.173333
1,1990-01-02,-15.333333,-8.233333,73.666667,66.666667,1.833333,4.666667,33.533333,39.600000,276.000000,0.356667
2,1990-01-03,-18.200000,-16.433333,72.333333,67.000000,0.000000,0.000000,24.400000,30.966667,280.000000,0.346667
3,1990-01-04,-16.700000,-10.300000,76.333333,67.333333,0.733333,4.000000,17.166667,23.900000,233.666667,0.256667
4,1990-01-05,-14.000000,-6.266667,75.666667,68.333333,0.766667,3.666667,24.200000,27.966667,262.333333,0.350000
...,...,...,...,...,...,...,...,...,...,...,...
12049,2022-12-28,-14.533333,-12.333333,72.000000,63.000000,0.900000,2.000000,18.333333,22.766667,264.666667,0.333333
12050,2022-12-29,-14.633333,-12.566667,73.000000,67.333333,0.000000,0.000000,16.166667,22.133333,279.333333,0.343333
12051,2022-12-30,-10.633333,-5.066667,77.666667,66.000000,2.300000,8.666667,10.333333,16.400000,194.666667,0.276667
12052,2022-12-31,-0.900000,2.333333,89.333333,80.333333,5.266667,11.333333,19.900000,26.400000,245.333333,0.240000
12053,2023-01-01,-5.200000,-1.333333,86.666667,83.333333,5.000000,5.000000,11.066667,18.933333,293.666667,0.176667

### Durchschnitt pro Monat

In [97]:
Newfoundland_and_Labrador_mean['time'] = pd.to_datetime(Newfoundland_and_Labrador_mean['time'])

# Monats-Durchschnitt für alle Variablen
Newfoundland_and_Labrador_mean = (
    Newfoundland_and_Labrador_mean
    .set_index('time')
    .resample('MS')
    .mean()
    .reset_index()
)

Newfoundland_and_Labrador_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm)
0,1990-01-01,-17.311828,-13.080645,76.569892,69.473118,1.537634,3.580645,16.498925,23.152688,223.000000,0.243226
1,1990-02-01,-21.377381,-16.767857,71.452381,62.428571,1.534524,3.488095,17.604762,24.186905,245.035714,0.297857
2,1990-03-01,-12.329032,-7.993548,74.258065,62.913978,1.441935,2.612903,16.897849,22.473118,257.720430,0.704409
3,1990-04-01,-3.592222,0.233333,79.622222,66.577778,2.713333,5.822222,16.294444,22.815556,191.033333,1.249889
4,1990-05-01,1.768817,5.438710,78.698925,63.365591,2.647312,4.440860,15.141935,20.783871,167.774194,1.862688
...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.550000,14.902222,81.588889,64.466667,5.596667,7.200000,15.535556,21.912222,212.022222,1.657000
393,2022-10-01,7.200000,10.531183,79.989247,64.075269,2.281720,4.935484,16.698925,23.100000,215.731183,1.153441
394,2022-11-01,-3.124444,-0.148889,79.311111,68.666667,3.460000,7.866667,16.605556,24.500000,224.722222,0.515222
395,2022-12-01,-6.889247,-3.804301,83.645161,76.311828,3.149462,6.236559,16.826882,23.213978,175.440860,0.267634
396,2023-01-01,-5.200000,-1.333333,86.666667,83.333333,5.000000,5.000000,11.066667,18.933333,293.666667,0.176667

In [98]:
# Jahr und Monat extrahieren
Newfoundland_and_Labrador_mean['Year'] = Newfoundland_and_Labrador_mean['time'].dt.year
Newfoundland_and_Labrador_mean['Month'] = Newfoundland_and_Labrador_mean['time'].dt.month
Newfoundland_and_Labrador_mean

,time,temperature_2m_mean (°C),temperature_2m_max (°C),relative_humidity_2m_mean (%),relative_humidity_2m_min (%),precipitation_sum (mm),precipitation_hours (h),wind_speed_10m_mean (km/h),wind_speed_10m_max (km/h),wind_direction_10m_dominant (°),et0_fao_evapotranspiration (mm),Year,Month
0,1990-01-01,-17.311828,-13.080645,76.569892,69.473118,1.537634,3.580645,16.498925,23.152688,223.000000,0.243226,1990,1
1,1990-02-01,-21.377381,-16.767857,71.452381,62.428571,1.534524,3.488095,17.604762,24.186905,245.035714,0.297857,1990,2
2,1990-03-01,-12.329032,-7.993548,74.258065,62.913978,1.441935,2.612903,16.897849,22.473118,257.720430,0.704409,1990,3
3,1990-04-01,-3.592222,0.233333,79.622222,66.577778,2.713333,5.822222,16.294444,22.815556,191.033333,1.249889,1990,4
4,1990-05-01,1.768817,5.438710,78.698925,63.365591,2.647312,4.440860,15.141935,20.783871,167.774194,1.862688,1990,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2022-09-01,11.550000,14.902222,81.588889,64.466667,5.596667,7.200000,15.535556,21.912222,212.022222,1.657000,2022,9
393,2022-10-01,7.200000,10.531183,79.989247,64.075269,2.281720,4.935484,16.698925,23.100000,215.731183,1.153441,2022,10
394,2022-11-01,-3.124444,-0.148889,79.311111,68.666667,3.460000,7.866667,16.605556,24.500000,224.722222,0.515222,2022,11
395,2022-12-01,-6.889247,-3.804301,83.645161,76.311828,3.149462,6.236559,16.826882,23.213978,175.440860,0.267634,2022,12
396,2023-01-01,-5.200000,-1.333333,86.666667,83.333333,5.000000,5.000000,11.066667,18.933333,293.666667,0.176667,2023,1

In [99]:
import os

#Datei speichern
output_path = "../data/cleaned_Newfoundland_and_Labrador_monthly_mean.csv"

# Sicherstellen, dass das Verzeichnis existiert
os.makedirs(os.path.dirname(output_path), exist_ok=True)

Newfoundland_and_Labrador_mean.to_csv(output_path, index=False)

## Prince Edward Island